### ISSUE TITLE
cs-studio eol and code format conventions

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1056]
The repository should use a consistant
- eol 
- java code format

For eol the repository has both CRLF and LF

For the java code format currently the repository is a mix of 
1. eclipse convention (tab size=4)
2. java convention (tab size=8)
3. java convention with no tabs (only spaces)

prior discussion #1054

**Comment by berryma4** [comment]
I already made one at #1055 :+1:
