### ISSUE TITLE
Update to Eclipse 4.5 Mars

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1064]
Eclipse 4.5 aka Mars is expected end of June 2015.

CS-Studio 'master' should then be updated to successfully build against it.

Things to gain for CSS:
 *  Customize Perspective Dialog is back (ITER had missed it).
 * UI responsiveness monitoring. We should include & enable this, which will put information about UI freezes, for example code that accesses files on the UI thread, into the log, so we can then fix frequent problems.
 * org.eclipse.core.runtime.jobs.JobGroup helps with creating jobs that use all CPUs (can also be done with Executors.newWorkStealingPool() if connection to Progress View is not required)
 * SWT on Linux can use GTK+ 3 (I see org.eclipse.swt.internal.gtk.version=2.24.23 in Help, About, Installation Detail, Configuration on our Linux computers, so that GTK 2 is also still supported).
 *  JFace StructuredViewer has IStructuredSelection getStructuredSelection(), no more casts.
 * In addition to the plugin_customization.ini, products can have a *.pde file with saved preferences.
 * General/Appearance has a "Presentation" schema that could be useful when using CSS in a meeting on projector display, where right now the fonts are all too small
 * IAdaptable.getAdapter() now uses generics, i.e. returns the requested type without casts
 * Mac OS X products are proper *.app (https://bugs.eclipse.org/bugs/show_bug.cgi?id=431116)

Things to gain in the IDE:
 * Nested/Hierarchical view of projects that might better reflect how we now structure things in the repository
 * Target platform "Reload" may help those who use remote repositories
 * E4 model editor etc. now included in IDE, no longer a separate install
 * Model fragments can use xpath.

For more: https://www.eclipse.org/eclipse/news/4.5/M7, which ends in links to ../M6, M5, ..

**Comment by berryma4** [comment]
I have also removed 32-bit builds

**Comment by berryma4** [comment]
0.23.1 tycho?
