### ISSUE TITLE
(Suggestion) Change "CSS" menu to "CS-Studio"

### ISSUE THREAD

**Issue by richardfearn** [ControlSystemStudio/cs-studio#1072]
Would it be good to change the "CSS" menu to "CS-Studio" ? It's specified [here](https://github.com/ControlSystemStudio/cs-studio/blob/master/core/ui/ui-plugins/org.csstudio.ui.menu/plugin.properties#L1).

**Comment by berryma4** [comment]
That would be great.

Thank you!
