### ISSUE TITLE
Macros substitution for linking containers broken

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1081]
On the master branch changes to the linking container have disabled the correct loading of the macros from the file being linked to.
Additionally system macro are also not correctly attached to the linking container( ${LCID} does not work)

In the LinkingContainerEditpart in the configureDisaplyModel(), we see that the macroMap for the display model is correctly updated and has all the required macros, with expected values.

opi files to recreate this issue have been added to the opi-regression-tests repository.
opening the screens in 3.3.x and 4.1.x  shows the discreapancy

**Comment by kasemir** [comment]
Does this also go back to #913?
After the path and script lookups #977 and #998 this would be yet another bug from the Linking container update.

**Comment by shroffk** [comment]
It would seem like this could quite probably be the change...since it has significantly changed the way the container is loaded.
