### ISSUE TITLE
Alarm icons: Flash

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1109]
Especially if active and acknowledged alarms are combined into one alarm table, it is helpful to have the active alarms stand out.
An option for flashing icons would provide this.

**Comment by utzeln** [comment]
Detailed requirements: the alarm priority symbol/icon shall flash at 2Hz until acknowledged by the operator. The flash timing of symbols must be synchronized for all flashing states. 
The alarm message must never flash.

Remark: on the mimics also, it is required that the component’s symbol (valve, pump, breaker...) shall flash at 2Hz until acknowledged by the operator. Same "look & feel" for the GUI regardless if it is boy or beast.
