### ISSUE TITLE
Alarm Configure individual columns width, weight and title

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1112]
- Not implemented, but it is agreed on as okay (preference w/o gui okay)
  - Kunal mentioned minimum width preference (lesson learned from logbook table / debian bug)
  - Kunal will verify 10 pixel minimum, check if after making width zero it can be re-sized again.

**Comment by shroffk** [comment]
For the vanishing table columns on Debian7 and Debian6 Kay's fix works. I verified with the databrowser property table and the alarmtable. The minumum width of 10 pixels is enforced - if the column is minimized beyond this it jumps back out to 10 pixels.

We can consider this aspect resolved and move on to implementing the preferences for allowing the configuration of width/weight/title
