### ISSUE TITLE
Putting together target definitions 

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1155]
Create a target:
We need multiple targets:
CS-Studio-4-0.target, .. for working with a released update site,
 and CS-Studio-Dev.target (while that is on master) for working with the development update site 

Options
1. List of remote update sites:
http://download.eclipse.org/releases/luna, 
http://download.controlsystemstudio.org/applications/4.1, …
Prepare target file for this,
open in IDE with target wizard, which downloads remote repos once,
set as active target
→ from now on you can work locally.

2. Have sources for maven, 3rd party, cs-studio core/app, build all once on local computer, then use that as target: output of the product build, composite repository.

Option 2 has no remaining advantage → Use only 1.

**Comment by berryma4** [comment]
code a thon finished!
