### ISSUE TITLE
Nullpointerexception in xygraph on load

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1199]
Kunal and I saw an NPE in XYGraph on load when inside LinkingContainer.
Error is based on setting some property, which calls getpv(), and that returns a null pv.
Likely related to the unfortunate create-pv, delete-pv, create-pv-again behavior of the LinkingContainer.

**Comment by berryma4** [comment]
#1200  ?

**Comment by shroffk** [comment]
The symptom has been addressed (NPE) in 1200.
The actual cause of it is the inherent connection problems and model updating of the linking container. 
I think we could close this issue after referencing this and 1200  in the main linking container ticket.
