### ISSUE TITLE
Linking container error when missing the linked opi_file

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1214]
As long as the <opi_file> target of a linking container widget is accessible, all is fine.
But if the target doesn't exist,  both the display editor and runtime refuse to load at all with an error "Cannot open /that/missing/embedded.opi".

Since this includes the editor, there is no way to for example enter a different opi_file target. Have to use a text editor for this, except even "Open With/Text Editor" is no longer available from the Navigator context menu unless I restart CSS.

When creating a new *.opi file with a new LinkingContainer, where the opi_file target is initially empty until one enters a valid *.opi file path, there is an error message "java.lang.Exception: Cannot open  (No such file or directory)" for the empty opi_file target.

**Comment by berryma4** [comment]
... right when I thought I could take a break from the linking container.

**Comment by kasemir** [comment]
Hi Eric:

Yes, this almost starts to suck.
I've fixed the easy part, the initially empty opi_file in the editor.

**Comment by kasemir** [comment]
Branch bug1214

**Comment by kasemir** [comment]
I think I fixed it. Now get a logged warning instead of the crashes.

**Comment by berryma4** [comment]
thank you

**Comment by kasemir** [comment]
Thanks for getting it onto the 4.1 branch.
