### ISSUE TITLE
Build error because of missing org.csstudio.simplepv

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1221]
A build of 'applications' fails with
```
[ERROR]   Missing requirement: org.csstudio.opibuilder 4.0.103.qualifier requires 'bundle org.csstudio.simplepv 1.0.0' but it could not be found
```

core/unorganized/unorganized-plugins/org.csstudio.simplepv is built, but it is not placed in unorganized/unorganized-repository/target/repository/plugins/ because the unorganized/unorganized-repository/category.xml does not include any feature which would cover org.csstudio.simplepv

--> Add a simplepv feature?

**Comment by kasemir** [comment]
@Kunal @berryma4  Adding a simplepv feature to core/unorganized would be the easiest thing to do right now, smallest number of changes.

On the other hand, simplepv is only used by opibuilder, so moving core/unorg/*simplepv* and apps/unorg/*simplepv* into opibuilder would consolidate it all in one place.

Preference?

**Comment by berryma4** [comment]
I would vote to add them to opibuilder, so it's not mistaken as a core api.

**Comment by kasemir** [comment]
Yes, "not mistaken as a core api" is a good reason for moving it to / hiding it in the opibuilder.

I'll do that.

**Comment by berryma4** [comment]
Added to master and 4.1.x
