### ISSUE TITLE
Scan editor handling of 'load'. Direct 'save' from monitor.

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1297]
Some SNS beam lines have a need to inspect past scans, save them, resubmit them.

Right now that can be done by opening a past scan in the editor, then save or submit from there.

Issue 1: Loading can take time and freezes the GUI. Faster would be good, but freezing is the main thing to be fixed.

Issue 2: Would be convenient to offer direct "Save As" and "Re-submit" actions in scan monitor context menu to skip the load-into-editor step which is often not really needed.

**Comment by berryma4** [comment]
This is great!!!  I just got the request for Issue 2 today!
