### ISSUE TITLE
BOY Confirm Dialog shall propose only Yes and No options?

### ISSUE THREAD

**Issue by utzeln** [ControlSystemStudio/cs-studio#1312]
The current confirmation dialog from boolean control widgets (show confirm
dialog property) or from script (GUIUtil -> openConfirmDialog) have 3 buttons:

    Cancel, No and Yes.

The Cancel behaviour compared to No seems the same.

Do we still need the cancel option or can we just have the Yes and No options?

**Comment by kasemir** [comment]
I agree that the dialog called from boolean widgets should just have a yes/no.
The GUIUtil `openConfirmDialog()` just returns a boolean, so you're right again that just yes/no would make more sense.

**Comment by berryma4** [comment]
can we get this on master?
