### ISSUE TITLE
How to display a 1-d array PV ?

### ISSUE THREAD

**Issue by firstzp** [ControlSystemStudio/cs-studio#1323]
Hello, how to display a 1-d array PV in CSS?
I have a 1-d array PV and it can be changed timely. If I use X-Y Graphy widget  to display it, it can't display correct when the value is changed.

**Comment by firstzp** [comment]
![20150901154612](https://cloud.githubusercontent.com/assets/11642433/9598748/ae8b447a-50c0-11e5-9c69-49a361a76d5c.png)

**Comment by berryma4** [comment]
What version of CS-Studio are you using?
Is BOY using pvmanager as the pv connection layer?
(org.csstudio.opibuilder/pv_connection_layer=pvmanager)

**Comment by berryma4** [comment]
Actually, I just tried this.  In probe, please show "metadata" from the drop down in the right corner.
I bet it changed from a VDoubleArray to a VString

**Comment by berryma4** [comment]
I may be wrong, @shroffk, but I don't think probe supports writing to an array.
But, if you use the "Array" widget in BOY, you should see the graph responding to changes of the local variable.

**Comment by shroffk** [comment]
What is not displayed correctly?
Are the values not changing?

Try this example and let me know if you still have problems
https://dl.dropboxusercontent.com/u/41120817/array.opi

**Comment by berryma4** [comment]
I believe the problem is, people assume the format for entering arrays in Probe is how it is displayed (ie. [1,2,3,4,5]), but this is interpreted as a VString.

**Comment by shroffk** [comment]
It seems like the array is entered correctly
loc://test(1,2,3)

**Comment by berryma4** [comment]
In probe, look at the details.  After initialization it says vdoublearray.
If you enter [1,2,3] in the probe new value text box, the type changes to a
vstring.

**Comment by shroffk** [comment]
Ok,
In any case, the way I use 1-D arrays is as shown in the example....
you can change the values
add/remove values
The plot keeps updating

**Comment by firstzp** [comment]
It can correct display the value right now!
Thank you for your help!
![20150902112159](https://cloud.githubusercontent.com/assets/11642433/9622419/4ee66090-5165-11e5-88fa-d65ab2a3f6fc.png)
Also, the buffer size of X-Y Graph and the size of 1-D array PV should be the same. And it can correctly update when the value of 1-D array PV changed.

**Comment by firstzp** [comment]
The problem may be the format of probe!

**Comment by shroffk** [comment]
Great
1. Displaying and writing to 1-D array works in BOY (XYGRaph, line plot, array....)
2. Probe does not support writing to Arrays - creating a new ticket ()
