### ISSUE TITLE
If you drag an OPIView out of the main window, it is repositioned

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1326]
There is logic in `OPIView.java` to reposition a view if it has been opened from the navigator.

However, if you drag a view out of the main window, it resizes and also attempts to move to the location specified in the OPI file.

The resizing may be correct behaviour.  However, we have users that say that if you drag a view out then it should stay where it was put!  I agree.

**Comment by willrogers** [comment]
@jbobnar I expect that you may need to make some changes after this commit to manage RCP and RAP.

Any comments on the changes are welcome.

**Comment by kasemir** [comment]
Can this be closed since the pull request fixed it?

**Comment by willrogers** [comment]
Yes, this is done.
