### ISSUE TITLE
Data browser Axis labels

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1332]
With the new Databrowser the aim is to maximize the plot area.

There are a few properties which would significantly improve that:

- Allowing the Time Axis Title to be hidden would save a lot of wasted space as show in the example below, the axis labels make the "Time" title quite redundant, having a checkbox in the Time axis tab to show or hide this title could save a lot of screen space.

Merging the Font of all the Axis though convenient makes it difficult to customize the plot.
![image](https://cloud.githubusercontent.com/assets/2111304/9774078/4eb6bba6-5714-11e5-9970-612118c80c57.png)

- Allowing each Axis to have its own font would allow screen developers to select the most appropriate font based on the Axis Title, A Axis with many traces and a long name could be configured to have a smaller font

**Comment by shroffk** [comment]
![image](https://cloud.githubusercontent.com/assets/2111304/9774337/cc214466-5715-11e5-8f21-f26338619ac7.png)

The Time Axis Title can be toggled on or off
![image](https://cloud.githubusercontent.com/assets/2111304/9774391/327cd888-5716-11e5-949b-29b8c09dbe70.png)

Each Axis has its own label and scale fonts
![image](https://cloud.githubusercontent.com/assets/2111304/9774383/235491de-5716-11e5-9918-c99ce2db75ed.png)

**Comment by kasemir** [comment]
How about just removing the Time axis title? No option, it's simply gone?

**Comment by shroffk** [comment]
I think Removing Time Axis Title complete is great....it would also make the code much cleaner.

**Comment by willrogers** [comment]
I just asked a couple of users and we couldn't see any need for a label saying 'Time' on the axis.

**Comment by berryma4** [comment]
Sounds great to me.

**Comment by berryma4** [comment]
Can we have a pull request for master too

**Comment by shroffk** [comment]
Both this and #1304 should be merged but have conflicts.
Is there any plan to merge the bug fixed and additions from 4.1.x to master branch?

**Comment by kasemir** [comment]
Yes, there are merge conflicts.

My leaning was cherry-picking whenever I did something to one branch to get that onto the other, then fixing the conflicts for just that, instead of trying to merge all of 4.1.x back to master.

**Comment by shroffk** [comment]
Fixed and merged in to both 4.1.x and master
