### ISSUE TITLE
Minor problems with EDM conversion

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1335]
Conversion problems:

* PV name conversion produces invalid results since assertions are used and the `-ea` command-line flag is not generally used
* EDM and CSS treat empty macros differently
* Changing colour of 2D profile monitor is not supported
* 'Toggle' and 'push' behaviour of BooleanButton (EDM Button) is incorrect

Test problems:

* Using both junit3 and junit4 features in `EdmConverterTest` appeared to cause some problems on Jenkins, even though local Maven builds worked.
* Tests fail because:
 * Converted widgets are now one pixel bigger
 * The structure of the `EdmColor` class has changed

**Comment by willrogers** [comment]
While I'm on this, I'll move all the tests to JUnit 4.

**Comment by berryma4** [comment]
can we close this?

**Comment by willrogers** [comment]
Yes, thanks.
