### ISSUE TITLE
Logbook review and sign operation fails to get selected log entries

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1345]
The problem arises from the removal of the adapter for LogEntry to LogEntryBuilder (This was to avoid the "reply" command to attached to a selection of the LogEntryBuilder which is also used by all "create log entry" and thus show up in all applications that provide a "create log entry").

**Comment by berryma4** [comment]
on master please too!

**Comment by shroffk** [comment]
yes, sure
