### ISSUE TITLE
PV preference page fails

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1384]
![image](https://cloud.githubusercontent.com/assets/854021/10431739/b584d10e-70d4-11e5-9364-da459a477726.png)

**Comment by berryma4** [comment]
@shroffk

**Comment by kasemir** [comment]
That would make sense, because I see a build error in code mentioned in #1171 where the pvmanager.ui cannot be built.

**Comment by shroffk** [comment]
This is strange, are you building all of core or just the utility module

**Comment by kasemir** [comment]
>This is strange, are you building all of core or just the utility module


I use a composite repo

https://github.com/ControlSystemStudio/org.csstudio.sns/tree/master/css_repo
that lists the locally built repository/target/repository for maven-osgi-bundles, 3rd party, core, applications, and then build all like this:

(cd maven-osgi-bundles; mvn clean verify)
(cd cs-studio-thirdparty; mvn clean verify)
(cd cs-studio/core; mvn clean verify)
.. and that last step fails with

[INFO] Resolving dependencies of MavenProject: org.csstudio:org.csstudio.utility.pvmanager.ui:3.2.0-SNAPSHOT @ /home/ky9/git/cs-studio/core/utility/utility-plugins/org.csstudio.utility.pvmanager.ui/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.csstudio.utility.pvmanager.ui 3.2.0.qualifier
[ERROR]   Missing requirement: org.csstudio.utility.pvmanager.ui 3.2.0.qualifier requires 'package org.diirt.vtype 3.0.0' but it could not be found

**Comment by shroffk** [comment]
Does the remote diirt  p2 repository get added to the list of repos?
>> Adding repository http://diirt.download.controlsystemstudio.org/diirt/3.0.1

**Comment by kasemir** [comment]
That's the issue for me!
core/pom.xml lists http://diirt.download.controlsystemstudio.org/diirt/3.0.1 as part of the cs-studio-sites profile, which I disable by defining the cs-studio property since I want to use only locally built CSS artefacts.

So I'd either have to build diirt locally, or list the remote dirt repo in my composite repo.

**Comment by willrogers** [comment]
I find that the `core` composite repo hasn't been updated to include the `diirt` repo anyway...

**Comment by kasemir** [comment]
I've updated the docbook: Full build needs to also clone diirt, build that, then list the diirt/p2/target/repository in the composite repo. With that, my cs-studio/core builds again.

So none of that helps at all with Eric's original question on the PV preference UI being broken.

**Comment by shroffk** [comment]
We are being too proactive with fixing things :)
The core p2 repo description has a 2 entries for diirt... @berryma4 is fixing it

**Comment by berryma4** [comment]
fixed.

**Comment by shroffk** [comment]
Should this issue be closed now?
