### ISSUE TITLE
OPIShellSummary breaks OPIRunner perspective

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1408]
This is odd.  One of our users reported that when the `OPIShellSummary` view is opened, opening views in different stacks in the OPIRunner perspective stopped working - all new OPIViews are opened in the same stack.

I can fix this by removing the `OPIShellSummary` view from the category `org.csstudio.opibuilder.views`, but I don't understand *why* this works.

@kasemir, any ideas?

**Comment by kasemir** [comment]
No, I don't understand.

The category `org.csstudio.opibuilder.views`, which shows up as "BOY" in the view listing, is used by all the "OPI View" views `org.csstudio.opibuilder.opiView`, `org.csstudio.opibuilder.opiViewLEFT`, ...

Your fragment _adds_ another view to that category. I would worry if the OPIShellSummary used a view ID that's already used by the OPI Views, but your view ID is unique.
One thing that might make a difference: All the other views in the `org.csstudio.opibuilder.views` category allow multiple instances, the OPIShellSummary doesn't. . which makes sense, but maybe there's a a quirk in Eclipse that doesn't allow this?

**Comment by willrogers** [comment]
@shroffk makes a similar comment here; https://github.com/ControlSystemStudio/cs-studio/pull/1374

I can't tell if this is referring to OPIShells (the same problem) or workbench windows (a similar problem).

**Comment by willrogers** [comment]
@shroffk can you confim whether this is fixed or not?  I believe it is associated with the new view as described above.

**Comment by berryma4** [comment]
fixed?

**Comment by willrogers** [comment]
Sort of.  I expect we will come back to this but you can close this ticket now.

**Comment by shroffk** [comment]
Yes, the scope of this ticket has been address and resolved.
As will pointed out both this as diirt configuration might need more work later
