### ISSUE TITLE
PVManager deadlock fix needs to be added to diirt

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1421]
https://github.com/ControlSystemStudio/pvmanager/commit/32275791b13cd2e0f209e7720006127a221ccc91

**Comment by shroffk** [comment]
For more references:
https://github.com/ControlSystemStudio/cs-studio/issues/1174

The current solution should be treated as a temporary patch.

**Comment by berryma4** [comment]
Do you need to do a diirt release, and point the core/application poms to the new release?
