### ISSUE TITLE
BOY Example 1_2_WidgetExamples.opi does not render

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1456]
runtime:
![image](https://cloud.githubusercontent.com/assets/854021/11244329/0158d59e-8ddb-11e5-922a-86cb5c0def9a.png)

editor:
![image](https://cloud.githubusercontent.com/assets/854021/11244342/20dd102e-8ddb-11e5-8562-84be2e060fa5.png)

**Comment by shroffk** [comment]
Was there an exception when you opened this page?

In the nsls2 development product, the page takes a significant amount to time to open (10s of seconds). However the page does successfully open and dispplays most widgets

The problem I see is the dotted uninitialized pv errors persist on the boolean symbol widget even after a value is set to them

![image](https://cloud.githubusercontent.com/assets/2111304/11342197/2006d6c4-91d4-11e5-9f35-a194350dfb4b.png)

**Comment by berryma4** [comment]
After fixing features, and removing pvmanager 2.x references #1470 this has gone away
