### ISSUE TITLE
"Name of user" lower rectangle too small to read username

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1485]
Lower left corner:
![image](https://cloud.githubusercontent.com/assets/854021/11504081/8cf0abc8-9811-11e5-8cf1-432f346fb840.png)

**Comment by berryma4** [comment]
@kasemir

**Comment by kasemir** [comment]
Is that on windows? Or on a newer Linux setup?

**Comment by berryma4** [comment]
Windows 7, I believe Dylan it's setting our on Linux.

**Comment by berryma4** [comment]
@dylan171, which version of Linux do you see this on?

**Comment by berryma4** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471313

**Comment by berryma4** [comment]
@kasemir I've submitted a workaround.  I had to add a label, so now a "-" precedes the logged in box.
Are you okay with this, until the eclipse issue is fixed?

**Comment by kasemir** [comment]
I'm OK with that. Maybe add
```
<!-- Workaround for https://bugs.eclipse.org/bugs/show_bug.cgi?id=471313 -->
```
to the plugin.xml change.

**Comment by berryma4** [comment]
I added the note.
Thank you!

**Comment by kasemir** [comment]
Thanks for fixing this before I've ever noticed that there's a problem!
