### ISSUE TITLE
opi-regression-tests - RulesTests - General_rule.opi

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1486]
General_rule.opi
Third one down, I'm not sure what it's suppose to do, but it does nothing.
![image](https://cloud.githubusercontent.com/assets/854021/11509422/057bd832-982c-11e5-9fce-2c9228d650e2.png)

**Comment by shroffk** [comment]
https://github.com/ControlSystemStudio/opi-regression-tests/commit/b8db54632503f7dbacef6be5efa3e228b4dcd3e8

This can be closed
