### ISSUE TITLE
Allow user to input all selected PVs to same value axis using Archive Search function in CSS Browser

### ISSUE THREAD

**Issue by tsouthern** [ControlSystemStudio/cs-studio#1517]
From: Window -> Show View -> Archive Search  

The user can select multiple PVs to display in Browser plot. It would be nice, if the user could have an option to have all selected PVs placed on the same vertical axis when they are dropped into the browser display. 

One ends up viewing nothing but axes on browser, if too many pvs are selected.  
<img width="1439" alt="Screen shot of browser after dropping multiple pvs to display" src="https://cloud.githubusercontent.com/assets/7449689/11765237/cb8a9e84-a11c-11e5-8434-352b87f05f75.png">

Perhaps a dialog similar to when adding a PV manually could be used. It gives the user an option to select the axis to display the pv.  
<img width="610" alt="screen shot 2015-12-12 at 10 23 52 pm" src="https://cloud.githubusercontent.com/assets/7449689/11765305/11168826-a11f-11e5-85b0-c2c9ad02833f.png">

**Comment by kasemir** [comment]
![add_multiple](https://cloud.githubusercontent.com/assets/1932421/11876042/a081cfc2-a4b5-11e5-8f7a-285a583a5294.png)

Implemented it by opening the add-PV dialog, which has been updated to handle multiple PVs.
The dialog still suggests a "new" axis for a single PV.
When adding multiple PVs, the dialog suggests to add them all to the last axis.
