### ISSUE TITLE
Double-click in archive search view should open a data browser editor

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1521]
Right now, when you've used the archive search in data browser you then have to right-click on the item in the search view and select Data Browser.  Because the archive search view is part of the data browser it seems natural that double-clicking on this element would open the data browser editor.

I've got a commit that will implement this behaviour.  Our users are in favour.  What do you think @kasemir?

**Comment by willrogers** [comment]
https://github.com/dls-controls/cs-studio/commit/dc7fd26baeeacc75141adfb3dc8c09f86c501bd2

**Comment by kasemir** [comment]
OK, go ahead
