### ISSUE TITLE
"Edit OPI" appears in all context menus

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1531]
The "Edit OPI" menu item appears not only in the context menu of the OpiRuntime, where it makes sense, but also in the context menus of the Databrowser plot, PVTable, EPICS PV Tree, ...

The fix might be some incantation of `<visibleWhen>` checking if the `activePart` is  an org.csstudio.opibuilder.opiView, org.csstudio.opibuilder.opiViewTOP, ...

**Comment by kasemir** [comment]
@willrogers  Changing the "Edit OPI" menu contribution to the following fixes the problem for the most part.

 * The "Edit OPI" menu entry does still show up in the OPIView
 * It's no longer in the Databrowser, PVTable, EPICS PV Tree, ..

.. but then it's also no longer in the context menu of the standalone OPI Shell..

```
   <extension point="org.eclipse.ui.menus">
      <menuContribution allPopups="false"
            locationURI="popup:org.eclipse.ui.popup.any?after=additions">
         <command  commandId="org.csstudio.opibuilder.commands.editopi"
               icon="icons/edit.gif"
               label="Edit OPI"
               style="push">
            <visibleWhen checkEnabled="true">
               <with variable="activePart">
                  <instanceof value="org.csstudio.opibuilder.runmode.OPIView"/>
               </with>
            </visibleWhen>
         </command>
      </menuContribution>
   </extension>
```

**Comment by kasemir** [comment]
For what it's worth, the original behaviour is somewhat intermittent. 
Below are snapshots of the "Edit OPI" menu item appearing on non-OPI parts. Invoking the erroneous menu item once will result in message box "The chosen operation is not enabled" and it will then disappear until CSS is restarted.
But there are other times where it disappears. I have not determined what all makes it come and go.

![edit1](https://cloud.githubusercontent.com/assets/1932421/11881960/e00ae92c-a4d7-11e5-90da-7f890158e9bb.png)
![edit2](https://cloud.githubusercontent.com/assets/1932421/11881962/e014a61a-a4d7-11e5-9ae4-6e39eed078ad.png)
![edit3](https://cloud.githubusercontent.com/assets/1932421/11881961/e0147582-a4d7-11e5-905f-1d27274131f3.png)

**Comment by willrogers** [comment]
Yes, we have noticed this.  We will take a look.

@nickbattam

**Comment by kasemir** [comment]
Thanks for looking into it.
What might work:
1) Add the `menuContribution ..command  ..visibleWhen ..activePart .. instanceof ..OPIView` so that it works OK for all the RCP code (shows in OPIView, does not show erroneously elsewhere).
2) Add another solution for the OPI Shell. Since it's less integrated with RCP, none of the https://wiki.eclipse.org/Command_Core_Expressions may apply, but one could still try to hinge upon activeShell. If all fails, the OPIShell might have to add its own expression variable "opiShellActive" via http://www.vogella.com/tutorials/EclipseCommandsAdvanced/article.html#commmands_sourceprovider

**Comment by willrogers** [comment]
We think this is fixed.  Please close the ticket unless you know otherwise.
