### ISSUE TITLE
Alarm DIIRT plugin

### ISSUE THREAD

**Issue by jbobnar** [ControlSystemStudio/cs-studio#1535]
@shroffk org.csstudio.alarm.diirt.datasource is missing build.properties file

**Comment by shroffk** [comment]
@jbobnar  can we close this?

**Comment by jbobnar** [comment]
There is no build.properties in the master yet.
The file added by f3ea6c7 is missing the OSGI-INF folder.

**Comment by shroffk** [comment]
I don't understand...eclipse might just be messing with me

![image](https://cloud.githubusercontent.com/assets/2111304/12685930/f1ecac82-c694-11e5-816a-93cbcf36d396.png)
