### ISSUE TITLE
Text Update alignment isn't always correct

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1561]
Sometimes right-aligned or centred text is not in the right place.  In the images below, the incorrectly aligned one has not had its position recalculated because it has the same number of characters as the default `######`.

**Comment by willrogers** [comment]
Incorrect:

![screenshot-mps overview -1](https://cloud.githubusercontent.com/assets/2440055/12331332/fa09ee58-bae0-11e5-8452-a7a50e42413b.png)

Correct:

![screenshot-mps overview](https://cloud.githubusercontent.com/assets/2440055/12331279/cf5c0a42-bae0-11e5-9c12-3a2d770c7685.png)

**Comment by kasemir** [comment]
Thanks for fixing this.
