### ISSUE TITLE
Move ADL and EDM converters from opibuilder.feature to separate features

### ISSUE THREAD

**Issue by mfurseman** [ControlSystemStudio/cs-studio#1594]
At the moment the opibuilder feature contains the following plugins:
- org.csstudio.opibuilder.converter
- org.csstudio.opibuilder.adl2boy
- org.csstudio.utility.adlParser

As far as I know these are only useful to people who have existing EDM or MEDM files, I would like to move them to two separate features, for instance:
org.csstudio.applications.opibuilder.edm.feature
org.csstudio.applications.opibuilder.medm.feature

This would allow people who want these plugins to explicitly include the features in their product configurations.

**Comment by willrogers** [comment]
+1 

In particular in our product we have the 'ADL Parser' and 'ADL-2-BOY' perspectives, and they are not useful to us.

**Comment by kasemir** [comment]
We'd likely include both the EDM and MEDM support, but having them in optional, installable features instead of the primary opibuilder feature is of course fine.

**Comment by berryma4** [comment]
@shroffk, @willrogers, @utzeln, @mjclarke01, @jpenning, @ksdj
Please take note, this merge may require changing your product file.
