### ISSUE TITLE
Channelfinder hard codes uri parameter

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1654]
It seems the server uri is hard coded in the Activator.
 
https://github.com/ControlSystemStudio/cs-studio-thirdparty/blob/master/plugins/gov.bnl.channelfinder.api/src/gov/bnl/channelfinder/api/Activator.java#L27
Could we make this a property?

**Comment by shroffk** [comment]
This is debugging code that should just be removed.
