### ISSUE TITLE
Minor OPIBuilder issues

### ISSUE THREAD

**Issue by jbobnar** [ControlSystemStudio/cs-studio#1682]
The following issues related to opibuilder were found:

* Setting the horizontal alignment has no effect on the multiline text widget
* When linking container is reloaded all its connectors should be marked as "loadedFromLinkedOPI". If not, they are stored twice: once in the child OPI and once in the OPI containing the linking container.
* AbstractSWTWidgetFigure sometimes throws widget disposed exceptions.
* ShowMarcoAction should first display the message dialog and then print to console. Otherwise the console print might shift the focus from a modal dialog to the main window, blocking entire CSS (this is an issue on some linux systems).
* OPIRuntimePreferences: the major/minor severities text for the pulsing property is mixed up
* WidgetService should not allow widgets with duplicate ids.
* Focus traversal with tab and shift+tab should be reversed on the native widgets. Pressing the tab should move the cursor to the next widget, which is the widget that appears later in the opi file. At the moment it goes to the previous, which is non intuitive and inconsistent with the "Next Focus" property. The most obvious is when using the Array Widget.
* Unless specifically needed the dependencies should match the Mars version of eclipse plugins (ITER's build constraint). There is a case of ..e4.ui.workbench in opibuilder and several other dependencies in the new perspectives plugin.

**Comment by berryma4** [comment]
Focus traversal with tab relates to #456
