### ISSUE TITLE
How to contribute page is hopelessly out of date

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1686]
This page is incorrect.

https://github.com/ControlSystemStudio/cs-studio/wiki/HowToContribute

Does anyone mind if I update it and link from the front page of the wiki?

@kasemir @berryma4 @shroffk @jbobnar

**Comment by kasemir** [comment]
It's actually amazingly up to date, all ideas still apply, just needs links to github instead of sourceforge ;-)
By all means, go ahead and update.

**Comment by willrogers** [comment]
I have:

* Updated https://github.com/ControlSystemStudio/cs-studio/wiki/HowToContribute
* Added https://github.com/ControlSystemStudio/cs-studio/wiki/CodingGuidelines
* Added them to the front page of the wiki https://github.com/ControlSystemStudio/cs-studio/wiki

**Comment by willrogers** [comment]
You can close this ticket if you like.

**Comment by berryma4** [comment]
I added a fork part, and something about the meetings.
Also, I fixed the link "How to get Started" to point to this wiki page.
http://controlsystemstudio.org/contribute.html

Thank you @willrogers !
