### ISSUE TITLE
 CSS : AlarmConfigTool : Executable launcher issue 

### ISSUE THREAD

**Issue by GitHubTE** [ControlSystemStudio/cs-studio#1711]
I am trying to install BEAST, so using AlarmConfigTool. When I tried executing its command, I am getting attached error. Please help.

![capture1](https://cloud.githubusercontent.com/assets/16385196/14285353/c1ea4ebe-fb68-11e5-932b-434c9a73d5a1.PNG)

**Comment by kasemir** [comment]
This could mean that you downloaded the 32 bit executable but you are on a 64 bit computer, or vice versa.
