### ISSUE TITLE
Alarm email notification content with line break

### ISSUE THREAD

**Issue by utzeln** [ControlSystemStudio/cs-studio#1715]
Example of current notification email:

PV: UTIL-S15-AG91:BUSBAR1 - Description: OK alarm: B91 MV busbar state - Alarm
Time: 2016/03/25 07:49:43.247 - Current Severity: OK - Current Status: NO_ALARM
- Alarm Severity: INVALID - Alarm Status: DISABLE_ALARM - Alarm Value: 0.0

It shall be possible to add line break in the email body using \r\n as the escape
sequence for new line in plain text, in order to have:

PV: UTIL-S15-AG91:BUSBAR1
Description: OK alarm: B91 MV busbar state
Alarm Time: 2016/03/25 07:49:43.247
Current Severity: OK
Current Status: NO_ALARM
Alarm Severity: INVALID
Alarm Status: DISABLE_ALARM
Alarm Value: 0.0

Is it OK to make such a change? Do we need a new setting to make it optional and by default we will have the current compact format?

**Comment by kasemir** [comment]
Just use your new format. The old one was indeed not very readable
