### ISSUE TITLE
CS-studio and maven/tycho

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#1723]
With the move to maven/tycho each cs-studio bundle now contains a pom file, after installing the tycho-configurator these projects can be directly imported as maven projects. Eclipse will create the .project, .classpath, and .settings files and it is no longer necessary to include these in each cs-studio bundle explicitly.

Note:
To handle access to javafx libraries it is necessary to configure eclipse preferences to ignore/warn 
Java->Compiler-> Errors/Warnings
Forbidden Access rules ---> warn

**Comment by kasemir** [comment]
Details on the Tyco configurator are in the docbook chapter on compiling CSS:

 * Open the Preferences menu item.
 * Locate entry Maven, Discovery.
 * Press Open Catalog, enter tycho, select the Tycho Configurator.
 * Press Finish and restart Eclipse when prompted.
After the restart, you should find the Tycho Configurator listed under the menu Help, Installation Details, Installed Software.
