### ISSUE TITLE
Data Browser: Allow configuration of 'Area's opacity

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1729]
The change from the 'average' line and the 'min/max' area color is currently fixed:
Line uses the color, area uses a more translucent version of that color.

--> Make the amount of translucency configurable.

**Comment by berryma4** [comment]
Suggestion taken from  BNL Operations feedback presentation.

**Comment by berryma4** [comment]
This is great!!!  Thank you so much @kasemir !

**Comment by berryma4** [comment]
@tashasummers @shroffk
