### ISSUE TITLE
Add new "Project" (Design and Development) workflow

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1741]
[Design and Delevopment.pdf](https://github.com/ControlSystemStudio/cs-studio/files/213342/Design.and.Delevopment.pdf)

**Comment by berryma4** [comment]
Site Representatives, please okay the new "Project" (Design and Development) workflow, or comment to edit.
 - [x] @berryma4 
 - [ ] @kasemir 
 - [ ] @shroffk  
 - [ ] @utzeln 
 - [ ] @mjclarke01 
 - [ ] @charlesHenryPATARD 
 - [ ] @ksdj 
 - [ ] @xinyuwu 
 - [ ] @jpenning 
 - [ ] @willrogers

**Comment by mattclarke** [comment]
Would it be better if it said the branch name **started** with "issue_xx" rather than **contains**?
Other than that it looks good to me

**Comment by charlesHenryPATARD** [comment]
- [x] @charlesHenryPATARD

Ok for me.

**Comment by berryma4** [comment]
@mattclarke, I can make that change.

**Comment by berryma4** [comment]
[Design and Delevopment.pdf](https://github.com/ControlSystemStudio/cs-studio/files/215667/Design.and.Delevopment.pdf)

**Comment by berryma4** [comment]
We have majority
