### ISSUE TITLE
Management Review Report

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1745]
Here is the Management Review Report from the review we had during the code a thon:
https://docs.google.com/document/d/1FhKhnjsFPFSBCrztP4WpXJly4dfLav4-y8Rz_DcTJWY/edit

Please comment on any additions, or check to call it done.

 - [x] @berryma4 
 - [x] @kasemir 
 - [x] @shroffk  
 - [x] @utzeln 
 - [ ] @mattclarke
 - [ ] @charlesHenryPATARD 
 - [ ] @ksdj 
 - [ ] @xinyuwu 
 - [x] @jpenning 
 - [x] @willrogers

Thank you everyone for your time!

**Comment by willrogers** [comment]
The bit on pages 4-6 doesn't seem to have been updated.

**Comment by berryma4** [comment]
Thank you, I removed the older sections.

**Comment by jpenning** [comment]
Thanks, Eric - no further additions from my side ... as you might have 
suspected :-)

Jörg.


On 12.04.2016 14:36, Eric Berryman wrote:
>
> Here is the Management Review Report from the review we had during the 
> code a thon:
> https://docs.google.com/document/d/1FhKhnjsFPFSBCrztP4WpXJly4dfLav4-y8Rz_DcTJWY/edit
>
> Please comment on any additions, or check to call it done.
>
>   * @berryma4 <https://github.com/berryma4>
>   * @kasemir <https://github.com/kasemir>
>   * @shroffk <https://github.com/shroffk>
>   * @utzeln <https://github.com/utzeln>
>   * @mjclarke01 <https://github.com/mjclarke01>
>   * @charlesHenryPATARD <https://github.com/charlesHenryPATARD>
>   * @ksdj <https://github.com/ksdj>
>   * @xinyuwu <https://github.com/xinyuwu>
>   * @jpenning <https://github.com/jpenning>
>   * @willrogers <https://github.com/willrogers>
>
> Thank you everyone for your time!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/ControlSystemStudio/cs-studio/issues/1745>
>

-- 
------------------------------------------------------------------------
Jörg Penning                             Cryogenic Controls Group(MKS-2)
phone:  +49-40-8998-2741                Deutsches Elektronen Synchrotron
fax:    +49-40-8994-3256                                    Notkestr. 85
e-mail: Joerg.Penning@desy.de                              22607 Hamburg
WWW-MKS2.desy.de                                                 Germany
------------------------------------------------------------------------

**Comment by kasemir** [comment]
Updated final section about idea/motivation for turning display builder into Eclipse project.

**Comment by berryma4** [comment]
We have a majority
