### ISSUE TITLE
Repeated tycho version numbers in top level pom.xml files

### ISSUE THREAD

**Issue by nickbattam** [ControlSystemStudio/cs-studio#1776]
The top level applications and core pom.xml files include separate version numbers for tycho and tycho-extras:

- cs-studio/applications/pom.xml
- cs-studio/core/pom.xml

```
<properties>
		<tycho.version>0.23.1</tycho.version>
		<tycho-extras.version>0.23.1</tycho-extras.version>
		...
</properties>
```

These definitions also appear in product and cs-studio-thirdparty repository poms.

The tycho and tycho-extras plugins have a matched release cycle. It make maintenance of the pom files simpler if we replaced the explicit tycho-extras.version with the tycho.version, i.e

```
<properties>
		<tycho.version>0.23.1</tycho.version>
		<tycho-extras.version>${tycho.version}</tycho-extras.version>
		...
</properties>
```

Can anyone see a problem with making that change?

**Comment by berryma4** [comment]
That would be fine.
