### ISSUE TITLE
unit test failed: org.csstudio.archive.vtype.TimestampHelperTest.testRoundUp

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1783]
https://openepics.ci.cloudbees.com/view/CS-Studio%20master/job/cs-studio-applications-archive-master/lastBuild/org.csstudio$org.csstudio.archive.vtype.test/testReport/org.csstudio.archive.vtype/TimestampHelperTest/testRoundUp/

**Comment by berryma4** [comment]
from pull request #1780

**Comment by berryma4** [comment]
@kasemir is this a bad test?

**Comment by kasemir** [comment]
I'll fix it.
It's a result of intriducing the TimestampFormats and then in there using "2012-01-19" instead of "2012/01/19", which we had in about half the cases, but it's not good if that time format ever ends up in file names, where the "/' would result in a path separator.

**Comment by berryma4** [comment]
Thank you!
