### ISSUE TITLE
oversized menu icon for Load Perspective

### ISSUE THREAD

**Issue by ajcarpente42** [ControlSystemStudio/cs-studio#1785]
Using Windows, under Menu CS-Studio, Utilities, the Load Perspective icon is oversized.
![cs-studio_error_menu_icon](https://cloud.githubusercontent.com/assets/19286167/15146648/9f8f37ac-168a-11e6-99d0-e252f7030ae0.png)

**Comment by kasemir** [comment]
Looks like that icon was added with #1627 .
@willrogers , should we change to a smaller (16x16) icon?

**Comment by willrogers** [comment]
Ah I see. I meant to check if we had a set of icons that we know are free to use. 

I'm fine if someone changes it or would you like me to find a better one?

**Comment by kasemir** [comment]
I can resize it.

**Comment by willrogers** [comment]
Great, thanks.
