### ISSUE TITLE
scan server: macros for set command device

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#1803]
I can use a macro for the device in a log command, but the macro is not replaced for the set command device.
Is this by design, or a bug?

**Comment by kasemir** [comment]
It's an omission. SetCommandImpl lacks the macro resolution in execute().
While at it, WaitCommandImpl lacks it in simulate().

Macros were only meant to work for device name, though. Not values.

**Comment by berryma4** [comment]
I was referring to the set command device field, not the set command value.
