### ISSUE TITLE
Spinnner widget decimal number format is inconsistent

### ISSUE THREAD

**Issue by nickbattam** [ControlSystemStudio/cs-studio#1822]
The spinner widget displays the (locale specific) 1000s separator when using DECIMAL format (e.g. 1,000,0041). Other widgets, like the TextUpdate, that offer DECIMAL format do not.

Looking in the code the number is formatted with a new DecimalFormat() object. For the TextUpdate widget the number is formatted via VTypeHelper using a new DecimalFormat("0").

I would like to update the spinner to use the same formatting as other widgets.

If any site requires the inclusion of the 1000s separator on the spinner I could add it as an option, but that would be a larger code change.

**Comment by kasemir** [comment]
I agree with your plan.
In general, we should prefer common, reproducible formats over locales.
CS-Studio displays should look the same no matter where you execute them. Having 1000s separators be added or removed, using either ',' or "'", having decimal separators change from '.' to ',' depending on where you look at a display is not good for control system tools.

**Comment by berryma4** [comment]
could you do a pull request to 4.3.x
