### ISSUE TITLE
BOY "init" scripts only run once on embedded displays

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1883]
Scenario:
'Parent' display has a script that updates the macros of a linking container, then triggers a re-load of the embedded display by setting the file name to "" and then back to the original file name.

The embedded display is updated with the new macros.
But if the embedded display has an "init" script, one that's triggered on a PV like "loc://trigger$(DID)(1)" or "=1", that init script will only execute once. It is not re-executed each time the embedded display is re-loaded.

In the display builder, the embedded "init" script will execute for each reload.

I assume the difference is that the display builder treats the embedded display as its own display, loading it in the background, starting its own runtime etc. For BOY, the embedded display is somehow merged into one big display widget tree, on the UI thread.

Unclear if this is worth fixing, since the overall handling of embedded displays, especially loading them on the UI thread, is problematic.

**Comment by berryma4** [comment]
Closing with won't fix
