### ISSUE TITLE
Test failure in org.csstudio.saverestore

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1886]
```
testGetBaseLevels(org.csstudio.saverestore.git.GitManagerTest)  Time elapsed: 0.024 sec  <<< FAILURE!
java.lang.AssertionError: expected:<base2> but was:<secondBase>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.csstudio.saverestore.git.GitManagerTest.testGetBaseLevels(GitManagerTest.java:302)
```

It looks like the ordering in `GitManager.getBaseLevels()` is not reliable.  We've got it failing reliably over here, but it seems to be passing on Travis.

**Comment by willrogers** [comment]
ttps://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles%28%29

"There is no guarantee that the name strings in the resulting array will appear in any specific order; they are not, in particular, guaranteed to appear in alphabetical order."

**Comment by nickbattam** [comment]
This is failing on both the 4.3.x and master branches

**Comment by berryma4** [comment]
@jbobnar

**Comment by berryma4** [comment]
Thank you @jbobnar!
