### ISSUE TITLE
NPE in calculatePrecision()

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1916]
#1870 supports the "Use precision from PV" for more than just the default format.

Problem is that not all VTypes actually have a format, i.e. it's null, and then org.csstudio.simplepv.VTypeHelper#calculatePrecision() gets an NPE
```
            displayPrecision = ((Display) pmValue).getFormat().getMinimumFractionDigits();
```

Need to check for getFormat() == null

**Comment by kasemir** [comment]
Thanks!

**Comment by berryma4** [comment]
Thank you!

**Comment by nickbattam** [comment]
Thanks!

**Comment by berryma4** [comment]
Thank you @nickbattam for the 4.3.x PR!!!
