### ISSUE TITLE
BOY "Open File" action results in changing editor

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#1944]
@dylan171 and @berryma4 brought up an issue with the "Open File" action in BOY.
It opens the file with some editor. The specific editor depends on what was used _last_ to open that file, resulting in somewhat unpredictable behavior for the next user on a beamline or in the control room.

The code behind the action is calling `SingleSourceHelperImpl#iOpenFileActionRun`
in the `o.c.opibuilder.rcp` plugin,
which in turn calls `org.eclipse.ui.ide.IDE.openEditor(.., IFile file, ..)`.
That uses `file.getPersistentProperty(EDITOR_KEY)` to determine which editor was used _last_ to open that file.

We could do this to always get the 'default' behavior:
```
  {   // Clear the last-used-editor info to always get the default editor
      file.setPersistentProperty(IDE.EDITOR_KEY, null);
      IDE.openEditor(page, file, true);
  }
```
Now the default editor, which can be configured via Preferences, General, Editors, File Associations, will be used, regardless of which editor was last used in the Navigator via "Open With..".

**Comment by nickbattam** [comment]
@kasemir That sounds like a sensible change

**Comment by dylan171** [comment]
I think our users would be happy with that change.

**Comment by berryma4** [comment]
Thank you!!!
