### ISSUE TITLE
Problem with sun.misc

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1963]
We cannot use pva in our product.  This appears to be related to #1855.

Although `com.diffplug.osgi.extension.sun.misc_0.0.0.jar` is in the plugins directory of the installation, it is not loaded at runtime:

```
osgi> ss misc
"Framework is launched."

id	State       Bundle
```

Trying to start the pvaccess plugin shows that `sun.misc` is missing:

```
osgi> start 796
gogo: BundleException: Could not resolve module: org.diirt.support.diirt-pva [796]
  Unresolved requirement: Import-Package: org.epics.pvaccess; version="[4.1.0,5.0.0)"
    -> Export-Package: org.epics.pvaccess; bundle-symbolic-name="org.epics.pvAccessJava"; bundle-version="4.1.3"; version="4.1.3"; uses:="org.epics.pvdata.pv"
       org.epics.pvAccessJava [952]
         Unresolved requirement: Import-Package: sun.misc
```

At startup we get an exception from diirt:

```
Found bundleentry://796.fwk99808631/META-INF/services/org.diirt.datasource.DataSourceProvider in org.diirt.support.diirt-pva_3.1.5 [796]
Providers [org.diirt.support.pva.PVADataSourceProvider]
Nov 21, 2016 1:21:35 PM org.diirt.util.config.ServiceLoaderOSGiWrapper$OSGiReflection loadClass
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
        ...
Caused by: java.lang.ClassNotFoundException: No class loader available for the bundle: org.diirt.support.diirt-pva_3.1.5 [796]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:587)
	... 38 more
```

Does anyone know how to resolve this?

**Comment by jbobnar** [comment]
Try adding this plugin fragment to your product:
https://github.com/ControlSystemStudio/cs-studio/tree/master/core/platform/platform-plugins/org.csstudio.jre6.fragment

**Comment by willrogers** [comment]
No, this doesn't seem to help either.  Now `org.csstudio.jre6.fragment_1.0.0.201611211441.jar` is in the built product instead of `com.diffplug.osgi.extension.sun.misc_0.0.0.jar`, but it still isn't loaded when I start CS-Studio:

```
osgi> ss jre
"Framework is launched."


id	State       Bundle
```

**Comment by willrogers** [comment]
Adding `com.diffplug.osgi.extension.sun.misc` directly to my product did work.

Should I need to add it to my product or should it be pulled in by a feature?

**Comment by kasemir** [comment]
I have it in the SNS product as well.
FWIW, I think the jre6.fragment is only used in RAP products, not SWT products.

**Comment by willrogers** [comment]
OK
