### ISSUE TITLE
Inspect Waveforms view should autoscale Y axis by default

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1975]
The Inspect Waveforms view doesn't autoscale the Y axis.  This makes it a bit fiddly to use unless the values happen to be in the range 0-10.

The recent changes to autoscale mean that autoscale can be turned on by default and any further manual changes will turn it off, which seems like better behaviour.

**Comment by kasemir** [comment]
Thanks for fixing this!
