### ISSUE TITLE
Optional cheatsheets from databrowser

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1989]
The databrowser manifest

```
applications/databrowser/databrowser-plugins/org.csstudio.trends.databrowser2/META-INF/MANIFEST.MF
```

has the following line:

```
 org.eclipse.ui.cheatsheets;resolution:=optional,
```

In order to see the cheatsheets, you need to add the plugin to a feature in your own product.  Is this intended?  It could easily be made a required dependency.

I realised this because I got an error from this plugin in Eclipse when developing.

**Comment by kasemir** [comment]
That may be optional because of RAP:
RAP doesn't have cheatsheets, so we can't require them.


________________________________

**Comment by willrogers** [comment]
Ah OK.
