### ISSUE TITLE
Select default archive engine in search view if configured

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#1999]
In the data browser preferences you can choose default archive engines for each archive URL.

It would be helpful if the archive search view selected these by default, since (in our case at least) you just have to manually select the top one in the vast majority of cases.

**Comment by kasemir** [comment]
If none is selected, it searches all of them, so you don't have to select any in your case.

But that may be more obvious if by default it started out with all selected.

**Comment by willrogers** [comment]
Done.
