### ISSUE TITLE
CS-STUDIO -> Utilities -> Search Logbook - the LogViewer Perspective is no more opened

### ISSUE THREAD

**Issue by rosarp** [ControlSystemStudio/cs-studio#2016]
@shroffk 

When opening search logbook, Log Viewer Perspective is not opened 

In Menu select :
CS-Studio -> Utilities -> Search Logbook

https://github.com/ControlSystemStudio/cs-studio/commit/e341dd334da154ac335dee865256b761c84e76b8#diff-4ca2cd8fe847f2d695265396691bef9c

Perhaps decoupling actions is still pending.
But, to have perspective opened on menu action, below changes are required.

```
diff --git a/applications/logbook/logbook-plugins/org.csstudio.logbook.viewer/src/org/csstudio/logbook/ui/OpenLogViewer.java b/applications/logbook/logbook-plugins/org.csstudio.logbook.viewer/src/org/csstudio/logbook/ui/OpenLogViewer.java
index a093f26..81d6185 100644
--- a/applications/logbook/logbook-plugins/org.csstudio.logbook.viewer/src/org/csstudio/logbook/ui/OpenLogViewer.java
+++ b/applications/logbook/logbook-plugins/org.csstudio.logbook.viewer/src/org/csstudio/logbook/ui/OpenLogViewer.java
@@ -44,7 +44,7 @@
         LogViewer.createInstance();
     }
     try {
-        //workbench.showPerspective(LogViewerPerspective.ID, window);
+        workbench.showPerspective(LogViewerPerspective.ID, window);
     } catch (Exception ex) {
         ExceptionDetailsErrorDialog.openError(
             HandlerUtil.getActiveShell(event),
```

Can we have this change so that, perspective is opened when search logbook menu is clicked?

**Comment by shroffk** [comment]
Yes, you are right - this was something that slipped through the cracks.
I have re enabled the search logbook functionality to open the log perspective.

Also cleaned up the shift plugins.
