### ISSUE TITLE
Databrowser autoscales to all buffered data, not visible data

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2017]
If you set autoscale on a databrowser Y axis, it will autoscale on all data contained in the `PVItem`.  However, this often contains historical data that has scrolled off the left-hand side of the plot, meaning that the autoscale no longer appears sensible.

Could it be changed so that it autoscales on the data visible in the plot?  From poking around I think this would be possible in `PlotProcessor.java`, by passing the x-axis range to `determineValueRange()`.

I can do this if you like.

**Comment by willrogers** [comment]
The change would look something like the pull request I just submitted.  It is a behaviour change etc so needs approval.

**Comment by kasemir** [comment]
Looks good to me.
Yes, it's a change, but one that matches the expectation of users.
Autoscaling based on some samples that aren't visible wasn't a good idea.
Thanks!

**Comment by willrogers** [comment]
Done!
