### ISSUE TITLE
Trouble Running css.exe

### ISSUE THREAD

**Issue by WilliamGoode** [ControlSystemStudio/cs-studio#2022]
I am attempting to run css on windows 7. After installing and attempting to run, I am shown the message shown in the attached image. I do not know what this message means or how to resolve the issue. I have verified that I am running Java version 1.8. Any help would be appreciated. 
![css_issue](https://cloud.githubusercontent.com/assets/12519863/21441158/da7b6d74-c853-11e6-8749-13041a03e6fe.jpg)

**Comment by berryma4** [comment]
Where did you download CS-Studio?  Which version?

**Comment by WilliamGoode** [comment]
I downloaded it using the following link. I believe it's version 4.1.1

https://ics-web.sns.ornl.gov/css/updates/apps/basic-epics-4.1.1-win32.win32.x86_64.zip

**Comment by berryma4** [comment]
64 bit java?

**Comment by WilliamGoode** [comment]
32 bit.

**Comment by berryma4** [comment]
You downloaded a 64 bit CS-Studio.  You will need the Oracle 64 bit java.

**Comment by WilliamGoode** [comment]
That was the problem. Thanks!
