### ISSUE TITLE
Overriding managed version 0.23.1 for tycho-p2 plugin.

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/cs-studio#2023]
Eclipse Neon shows the "Overriding managed version 0.23.1 for tycho-p2 plugin." warning messages on all `pom.xml` files containing **`<version>${tycho.version}</version>`**:
```
<groupId>org.eclipse.tycho</groupId>
<artifactId>tycho-p2-plugin</artifactId>
<version>${tycho.version}</version>
```
It would be great to revise all the pom files marked as problematic and fix them.

**Comment by nickbattam** [comment]
If any change is made to the use of `${tycho.version}` the same logic should be applied to the `tycho-source-feature-plugin`
 ```
   <artifactId>tycho-source-feature-plugin</artifactId>
   <version>${tycho-extras.version}</version>
```

**Comment by nickbattam** [comment]
The warning can be suppressed if we resolve the explicit version is required in these files:
```<version>${tycho.version}</version><!--$NO-MVN-MAN-VER$-->```

**Comment by willrogers** [comment]
I think this is a valid warning.  The Tycho version should be inherited from the parent pom, but we are redefining to (even though we are redefining to the same version).

I think I've fixed all five of these warnings in the cs-studio repo.  Can I close this ticket?

**Comment by claudio-rosati** [comment]
Still there in:

- org.csstudio.product
- org.csstudio.display.builder

I've removed the one in org.csstudio.product (see [#24](https://github.com/ControlSystemStudio/org.csstudio.product/pull/24)). For the one in Display Builder I would like to have @kasemir agree on that.

**Comment by kasemir** [comment]
Make a pull request for the display builder.

**Comment by claudio-rosati** [comment]
OK

**Comment by claudio-rosati** [comment]
Done: [#216](https://github.com/kasemir/org.csstudio.display.builder/pull/216)
