### ISSUE TITLE
New detail panel widget

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2051]
We (DLS) have developed a BOY widget that is like a properties panel but where each row can contain other widgets.  We've been using this widget for a while and now we'd like to share area detector screens that use it.

Can we put the widget in the main repo?  I think it should live in its own plugin, and we can support it.

cc @thomascobb

**Comment by willrogers** [comment]
It looks like this:

![detail](https://cloud.githubusercontent.com/assets/2440055/22251753/d88f21a4-e243-11e6-86f6-a75b02861807.png)

**Comment by berryma4** [comment]
Yes!

Please make a pull request.

**Comment by claudio-rosati** [comment]
Something similar I'll develop for Display Builder too. Would be interesting be able to import your (BOY) into mine (DB).

**Comment by willrogers** [comment]
Yes, that would be very helpful in allowing us to move from BOY to Display Builder.

Thanks!
