### ISSUE TITLE
Someone deleted the 4.4.x branch

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#2088]
It seems the 4.4.x branch has been deleted.
@willrogers, you made the last commit.  Can you push a new 4.4.x branch?

**Comment by berryma4** [comment]
Also, is it possible to make branch rules in github? (like in bitbucket, or gitlab)

**Comment by claudio-rosati** [comment]
Was my fault. I'm terribly sorry: I suposed to be on my forked version.

**Comment by berryma4** [comment]
I found the branch permissions in the github settings, we should have set this a long time ago.
I'm protecting all frozen branches and requiring pull request to master.  We were doing this already, but the setting will help accidents from happening.

**Comment by berryma4** [comment]
@shroffk , @kasemir , does anyone have an up to date 4.4.x?

**Comment by kasemir** [comment]
I have origin/4.4.x from ~24 hours ago

**Comment by willrogers** [comment]
I just pushed 4.4.x back - you might want to check it's in the right place but I think it is.

**Comment by berryma4** [comment]
ce79cda884fee3d1d27bed74a2410d2860c7b153 should be the last commit.

**Comment by kasemir** [comment]
I see eda3be3 as the last commit, and the origin/4.4.x that I had is the same that there's now.

**Comment by berryma4** [comment]
@willrogers perfect!  Thank you so much ... I was just going to try `git reflog`.  But all is well again!
I will set the permissions on the 4.4.x  branch.

**Comment by berryma4** [comment]
Thank you everyone!

**Comment by shroffk** [comment]
right, the last commit I have matches wills and Kays not the ce79cda

**Comment by berryma4** [comment]
Yes, sorry, my merge commit for that sha1 was the last.

**Comment by berryma4** [comment]
Okay, I've protected released and master branches on cs-studio, thirdparty, maven-osgi-bundles, and product repos.
That should cover preventative measures.
Thank you again!

**Comment by claudio-rosati** [comment]
Thank you and sorry again.
