### ISSUE TITLE
Missing preference page

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/cs-studio#2111]
Eclipse has teh **Startup and Shutdown** preference page.

![img1](https://cloud.githubusercontent.com/assets/10833922/23066835/bef32088-f51c-11e6-8e9f-bdc92bce194c.png)

Inside it the **Workspaces** sub-page allows managing the visited workspaces and define the behaviour at startup.

![img2](https://cloud.githubusercontent.com/assets/10833922/23066879/fd4673f8-f51c-11e6-8e05-56a4044cd771.png)

Moreover, the **Workspace** page is linking the **Startup and Shutdown** one just below the header.

![img3](https://cloud.githubusercontent.com/assets/10833922/23066916/278bb286-f51d-11e6-84d3-0b8e402375cd.png)

CS-Studio has a problem, not being able to find the org.eclipse.ui.preferencePages.Startup. How this can be solved? I've tried googling without success.

<img width="755" alt="img4" src="https://cloud.githubusercontent.com/assets/10833922/23067015/a19f701c-f51d-11e6-840a-01e97d13cdd1.png">

**Comment by jbobnar** [comment]
- If you want to use the exact preference page that Eclipse is using add the plugin org.eclipse.ui.ide.application to your product.
- Alternatively you can create a plugin that provides the definition of the extension point org.eclipse.ui.preferencePages and use the above name for its ID.

**Comment by claudio-rosati** [comment]
Your first point is exactly what I've tried to do using the teature editor on my product's feateures, but the editor didn't show me the org.eclipse.ui.ide.application plugin.

So after your suggestion, I've tried to add the plugin editing the features' XML file, built the product with Maven/tycho and now the property page appeared.

Thank you
