### ISSUE TITLE
Actions aren't executed on OPIShells

### ISSUE THREAD

**Issue by mfurseman** [ControlSystemStudio/cs-studio#2192]
The mechanism for resizing OPI Shell's merged in https://github.com/ControlSystemStudio/cs-studio/pull/1915 seems to have inadvertantly removed the code which binds the active OPI shell to a static field in that class. The result of this is that actions do not always work on the shells, such as show/hide toolbar on the XY-Graph. We will create a pull request to rectify this.

**Comment by willrogers** [comment]
Done.
