### ISSUE TITLE
The CSS Core ➜ Process Variables ➜ Loc DataSource help page needs to be updated

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/cs-studio#2249]
The last table on the page is outdated, not showing the `loc://pvname<VEnum>` type.

Probably the whole page has to be updated to the currently supported `log://` data souurce.

**Comment by willrogers** [comment]
The local PV part is my job.  Right now I can't build CSS due to a conflict between `cs-studio/core` and `diirt` - is that true for everyone?

**Comment by claudio-rosati** [comment]
I had the problem, now its ok. What you have to do is using the diirt/diirt GitHup projectm not the ControlSystemStudio/diirt one.

**Comment by claudio-rosati** [comment]
Another question about the local PV, it seems to me that VBoolean is not supported. Is ti correct? If yes, why?

**Comment by willrogers** [comment]
Historically, I think that VInt wasn't added because VDouble would suffice, and perhaps the same is true for VBoolean.  Do you have a specific need?

**Comment by kasemir** [comment]
In practice, there really is no VBoolean PV.
Boolean PVs, for example from bi, bo records, are VEnum with two states.

**Comment by claudio-rosati** [comment]
No, not a specific need. But when in the code I see the VBoolean class, I'm expecting to be able to use it also in the local PV because, semantically, a boolean is not an int, nor an enum.
