### ISSUE TITLE
Archive Engine does not Archive Arrays 

### ISSUE THREAD

**Issue by DominicOram** [ControlSystemStudio/cs-studio#2263]
At ISIS we recently upgraded our ArchiveEngine from version 3.1. 

It appears that in the latest version when a waveform PV is set to be archived the data is not saved into the database. A new entry is created in the sample table when the PV changes and the first element of the array is put into the float_val however the array_val remains null. This has been tested using float and char arrays, neither of which work.

**Comment by kasemir** [comment]
Have you checked if the engine is configured to use the `array_val` blob or not?
By default it's disabled, and then the values end in the array_val table vs. the samples.array_val blob:
```
org.csstudio.archive.rdb/use_array_blob=false
```

**Comment by kasemir** [comment]
I just tried with the latest from 'master', using the 'Demo' configuration which includes `sim://noiseWaveform(0,10,100,10)`. By default, it writes to the `array_val` table. When I change the configuration to ` org.csstudio.archive.rdb/use_array_blob=true`, it writes to the `sample.array_val` blob.

**Comment by DominicOram** [comment]
Oops! Thank you!
