### ISSUE TITLE
ScaledSlider and Knob widgets ignore drive limits from PV

### ISSUE THREAD

**Issue by nickbattam** [ControlSystemStudio/cs-studio#2305]
When the ScaledSlider widget is set to get limits from PV it sets the max and min scale limits to  UpperDisplayLimit (HOPR) and LowerDisplayLimit (LOPR). 

This update is done is a base class shared with a number of other widgets:
Monitor:- Guage, Meter, ProgressBar, Tank, Thermometer
Control:- Knob, ScaledSlider

For the 'monitor' widgets the DisplayLimits are probably the correct field to use. 

For the 'control' widgets should the max/min be set to the drive limits (DRVH and DRVL) rather than display limits to match behaviour in the TextInput (#1910) and SpinnerWidgets (#2302)?

**Comment by kasemir** [comment]
Yes, using the control limits is better than the display limits for 'control' widgets.

**Comment by nickbattam** [comment]
I'll do this then
