### ISSUE TITLE
Databrowser: precision of annotation values 

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2339]
Operator request:

When you add an annotation to the databrowser, you have no control of the precision of the value that is rendered. This means that when you're trying to show differences sometimes the annotation doesn't show that there is a difference at all.

Could we provide some way to specify precision?

**Comment by kasemir** [comment]
The precision is based on the current axis labels.

![ann1](https://user-images.githubusercontent.com/1932421/33609534-7b4be004-d996-11e7-8a50-89360647a1f2.png)

Zoom "in", and you get a higher precision:

![ann2](https://user-images.githubusercontent.com/1932421/33609549-87542488-d996-11e7-9569-b3b6a5d70560.png)

It is, however, just like the axis setting.
Maybe it should use the 'crosshair' precision, which is basically "one more digit":

![ann5](https://user-images.githubusercontent.com/1932421/33609572-9da8419c-d996-11e7-82b4-f151261897f6.png)

**Comment by willrogers** [comment]
Fixed with #2674
