### ISSUE TITLE
No log entry, send e-mail screenshot on first instance 

### ISSUE THREAD

**Issue by boryto** [ControlSystemStudio/cs-studio#2345]
There is a problem when creating fist screenshot instance after the CS-studio start. The image contains empty white canvas, with proper size, but with no content.  This problem is present on RHEL Linux systems with Gnome-3.  This only occurs on first instance, all other instances have no problem. 

![image](https://user-images.githubusercontent.com/5550006/33653163-052a35b4-da64-11e7-8d1a-ce0f1f1896fa.png)

**Comment by css-iter** [comment]
This is fixed by calling the gc.copyArea(image, 0, 0) twice. Looks like on fist call something is not properly initialized in new GC(drawable), which probably leads to the SWT and GTK internals.  

The overhead of calling the method twice is minimal.
