### ISSUE TITLE
combo control write value

### ISSUE THREAD

**Issue by lotrus** [ControlSystemStudio/cs-studio#2350]
Hello,
We can’t set a PV value using Combo in CSS 4.5, We have tried with the BOY Example ChoiceWidgets.opi and it does not seems to work either.
We have no issue with CSS 4.1 , did anything changed?
Best

**Comment by kasemir** [comment]
Which part doesn't work?

For `/BOY Examples/widgets/3_6_ChoiceWidgets.opi` to run, you need a record called `css:sine`, which you can for example get like this:

```
record(calc,"$(user):count") {
        field(SCAN,".1 second")
        field(INPA, "$(user):count.VAL")
        field(CALC, "A+1")
}

record(calc,"$(user):sine") {
          field(SCAN,".1 second")
        field(INPA, "$(user):count.VAL")
        field(CALC, "100*sin(A/10)")
        field(HIHI, "80")
        field(HHSV, "MAJOR")
        field(HIGH, "60")
        field(HSV, "MINOR")
        field(LOW, "-60")
        field(LSV, "MINOR")
        field(LOLO, "-80")
        field(LLSV, "MAJOR")
        field(HOPR,"125")
          field(LOPR,"-125")
}
```

Or read `/BOY Examples/softIOC.txt`


![combo](https://user-images.githubusercontent.com/1932421/34046063-a3cb4b88-e179-11e7-95fe-8b571541a2f4.png)

**Comment by lotrus** [comment]
We don't have trouble with the period ones.  The control that doesn't work is the combo control associated with the PV loc://myChoice.  We can change the value from blue to grey with the other controls but not with Combo Box_1 (label) or Combo. We are using the CSS SNS 4.5.

**Comment by kasemir** [comment]
Can't reproduce. I'm using the latest sources from the git master, and with both vtype.pv and pvmanager both combo boxes as well as the text input in the upper right corner work fine.
The tooltip on all widgets shows that loc://myChoice is of type VString

**Comment by lotrus** [comment]
We are realizing that it's not working only with sns-css-4.5.0-win32.win32.x86.zip available (nightly build of SNS), the 64 bits is ok.

**Comment by kasemir** [comment]
Same issue as #2413
