### ISSUE TITLE
Databrowser3: Context missing for databrowser3 opi to open in databrowser3

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#2363]
When you right click databrowser3 opi, the "open in databrowser" context seems to be missing.

**Comment by kasemir** [comment]
Right, need to add the "Open Data Browser" entry.
It's in the display builder widget, but not the BOY widget.

**Comment by kasemir** [comment]
Might take a little longer.
Megan prepared the code for opening the data browser is there, but just like her I'm lost in the chain from SWT -> Draw 2D Figure -> SWT-widget-inside-Draw2d-Figure -> FXCanvas -> Actual JFX plot and how to get the context menu added.

**Comment by kasemir** [comment]
Also added the show/hide toolbar entry to the context menu.
