### ISSUE TITLE
Databrowser3: Value Axes Color property has no effect

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#2364]
When I change the color in the Value Axes tab in Databrowser3, the axis color does not update.

**Comment by kasemir** [comment]
Right, need to support that.
Can we merge #2365 so that I can work on the sources without compiler errors?

**Comment by kasemir** [comment]
Since the changes are in the display builder repo, was able to fix it there against cs-studio from the jca_2361 branch.

**Comment by berryma4** [comment]
Thank you!
