### ISSUE TITLE
Command line access to EDM/EDL file converter

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#2385]
The EDM/EDL file converter #2228 can be called from within the UI.
For batch conversions it would be good to have command line access.
Suggestion is to build this into the CSS product, i.e. similar to the MEDM converter, #2342, the EDM converter will be callable from the command line, somewhat like this:

```
css -nosplash
   -application org.csstudio.opibuilder.converter.edl
    /path/to/file1.edl
    /path/to/file2.edl 
```

**Comment by berryma4** [comment]
You could open the UI and save the preference:
http://htmlpreview.github.io/?https://github.com/ControlSystemStudio/cs-studio/blob/master/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder.converter/html/Getting_Started.html

Or you could edit the configuration/plugin_customization.ini to include:

```
org.csstudio.opibuilder.converter/edm_colorlist_file=/CSS/color.list
org.csstudio.opibuilder.converter/output_opicolor_file=/CSS/color.def
org.csstudio.opibuilder.converter/output_opis_folder=/CSS/output
org.csstudio.opibuilder.converter/robust_parsing=true
org.csstudio.opibuilder.converter/open_opis=false
```
