### ISSUE TITLE
Update to Eclipse 4.7 Oxygen

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2401]
We want to update CS-Studio to build and run using Java 9. A prerequisite for that is to build against Eclipse Oxygen.

**Comment by berryma4** [comment]
let's update to the new diirt release and then branch first.

**Comment by willrogers** [comment]
Fine, there's no rush.

**Comment by kasemir** [comment]
Eric, you make it sound as if changing diirt is easier than updating to Java 9 ;-)

**Comment by berryma4** [comment]
master is open for updating to Oxygen.

**Comment by berryma4** [comment]
I merged ControlSystemStudio/cs-studio-thirdparty, did you have a branch for ControlSystemStudio/cs-studio?

**Comment by berryma4** [comment]
I made a pull request with the new urls.
We were able to remove efx, because it is now in the Eclipse Release Train (the oxygen url).

**Comment by berryma4** [comment]
I've also updated the common product urls, and added the java 9 vmarg
```java
--add-modules ALL-SYSTEM
```

**Comment by berryma4** [comment]
Also, with java 9, we should be able to use GTK3:
http://openjdk.java.net/jeps/283

**Comment by berryma4** [comment]
tried upgrading to e(fx)clipse 3.0.0
I had issues with the diirt jars/MANFEST resolving javafx.*
I tried adding extraClasspathElements for javafx to the tycho compiler, but this didn't work.
Out of frustration, rolling back to e(fx)clipse 2.4.0
I still removed:
all javafx imports, org.eclipse.fx.javafx from all requires (not needed anymore)

**Comment by claudio-rosati** [comment]
About e(fx)clipse... and JDK 11/OpenJFX 11

https://tomsondev.bestsolution.at/2018/08/04/supporting-openjfx-11-from-jdk11-onwards-in-efxclipse/
