### ISSUE TITLE
Download page is confusing

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2443]
If you go to http://controlsystemstudio.org and follow the links to Download, you end up with Eclipse update site, which is rarely what anyone wants.

http://controlsystemstudio.org/controlsystemstudio/current.html#

I think it should go straight to artifacts so people can download a runnable instance.

**Comment by willrogers** [comment]
Also, the ESS download page linked from here: http://controlsystemstudio.org/controlsystemstudio/current.html# now requires an ESS login @claudio-rosati

**Comment by claudio-rosati** [comment]
It should be ok now.

**Comment by willrogers** [comment]
Thanks, I can see it now.

**Comment by berryma4** [comment]
I've update the download page to go to the artifacts page first, and changed the name to binaries.
