### ISSUE TITLE
On a Value Axis 'Add' the automatic axis naming can create a duplicate of an existing name

### ISSUE THREAD

**Issue by skyfrench** [ControlSystemStudio/cs-studio#2455]
e.g.

When you right click and call 'Add Axis' from the Value Axes tab the new axis currently takes the name Value N where N is the number of existing value axes + 1.

Therefore if you currently have:
Value 1, Value 2, Value 3
Then delete the first one, leaving you with:
Value 2, Value 3
The next newly added axis gets the name Value 3 (2 + 1), giving:
Value 2, Value 3, Value 3

**Comment by willrogers** [comment]
Fixed
