### ISSUE TITLE
OPI won't start in standalone window unless JavaFX is available

### ISSUE THREAD

**Issue by Amadrath** [ControlSystemStudio/cs-studio#2470]
When I try to start an opi in standalone mode, I get the following error:
`2018-08-08 16:22:25.179 SCHWERWIEGEND [Thread 1] org.csstudio.logging.PluginLogListener (logging) - Unhandled event loop exception
org.eclipse.swt.SWTException: Widget is disposed`
And the Standalone OPI Summary shows:
`org.eclipse.core.runtime.CoreException: Plug-in "org.csstudio.opibuilder" was unable to instantiate class "org.csstudio.opibuilder.runmode.OPIShellSummary".`
I have tried this on an SNS and NSLS flavours. Has anybody a clue?

**Comment by kasemir** [comment]
Try to open the menu CS-Studio, Debugging, Logging Configuration.
If that also fails, you're using some JRE that lacks JavaFX.
Do you have an Oracle JDK that includes JavaFX?
Check Help, About, Installation Details, Configuration for *java*.

This will work:
```
java.vendor=Oracle Corporation
java.version=1.8.0_121
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.121-b13
```

If it's OpenJDK, or a RedHat installation of oracle-jre without jfx, it won't suffice.

**Comment by Amadrath** [comment]
The missing JavaFX was the problem. After installing 'openjfx' (for 'openjdk-8') the standalone windows opened.

**Comment by kasemir** [comment]
Good. That's by design. Several of the newer components use JavaFX for graphics, so they won't work unless that's available.

**Comment by willrogers** [comment]
I'm interested in how you installed 'openjfx', as that's not always very easy.

**Comment by Amadrath** [comment]
Simply: apt install openjfx

**Comment by willrogers** [comment]
Thanks. It looks like Debian is ahead of RedHat.
