### ISSUE TITLE
Download Page is Down

### ISSUE THREAD

**Issue by dhidas** [ControlSystemStudio/cs-studio#2492]
from here:
http://controlsystemstudio.org/controlsystemstudio/current.html

I get links to the different versions such as:
http://download.controlsystemstudio.org/updates/4.5

All seem to give an error message like:
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: updates/4.5
RequestId: FE48712496A83EDC
HostId: PfQTWRKQWKFYtFCXj1M2H/TzuU9OOxmSCbnjFA+0jvM3TrieCYYe02ZguxV77fWYo4k46GL8PkA=

**Comment by berryma4** [comment]
We should probably make our webpage more clear.
You will need to click the "Artifacts" tab, then click the "Download" button.
The link ends up being:
http://download.controlsystemstudio.org/release/4.5/

The update links:
http://download.controlsystemstudio.org/updates/4.5
are Eclipse p2 sites, not for people consumption, but for entering into Eclipse.

**Comment by willrogers** [comment]
I've said this before, I think the actual downloads should be the default.

**Comment by willrogers** [comment]
https://github.com/ControlSystemStudio/cs-studio/issues/2443

**Comment by berryma4** [comment]
I've update the download page to go to the artifacts page first, and changed the name to binaries.
