### ISSUE TITLE
execute OPI file as runtime mode directly

### ISSUE THREAD

**Issue by ss2016226088** [ControlSystemStudio/cs-studio#2544]
Hello

generally, on the navigator click run or open with OPI runtime mode.

but i want to make it easier with command line.

I found it can be possible with options like

./css --launcher.openFile <opi path>

but it doesn't work.

What I want is an environment where you can run the window standalone opi runtime immediately after double-clicking on the opi file, or give the run-time option to view the runtime without going through Edit mode.

please help.. :)

**Comment by berryma4** [comment]
This can be done with the OS.
For example, you windows packaging can add to the registry:
```
[Registry]
Root: HKCR; Subkey: ".opi"; ValueType: String; ValueData: "BOY"; Tasks: cssAssociation; MinVersion: 0.0,5.0; Flags: uninsdeletevalue 
Root: HKCR; Subkey: "BOY"; ValueType: String; ValueData: "BOY"; Tasks: cssAssociation; MinVersion: 0.0,5.0; Flags: uninsdeletekey 
Root: HKCR; Subkey: "BOY\DefaultIcon"; ValueType: String; ValueData: "{app}\applicationIcons\OPIRunner.ico"; Tasks: cssAssociation; MinVersion: 0.0,5.0; 
Root: HKCR; Subkey: "BOY\shell\open\command"; ValueType: String; ValueData: """{app}\cs-studio.exe"" --launcher.openFile ""%1 Position=Detached"""; Tasks: cssAssociation; MinVersion: 0.0,5.0; 
```
