### ISSUE TITLE
Detach only Runtime solution

### ISSUE THREAD

**Issue by ss2016226088** [ControlSystemStudio/cs-studio#2550]
Is there any solution or methods for detaching BOY Runtime mode?

I got some problems on detaching Only runtime mode.

I am still looking for cues.

I am thinking It can be possible but it's to hard for me..

1. how to build only Runtime mode? like
./Runtime /home/css/workspace/main.opi

then just opi file with runtime mode.

2. is there any option arguments or solutions?

I tried ./css --launcher.openFile /home/css/workspace/main.opi

but it doesn't work..

I have to solve this issues.. please help me :)

Thanks

**Comment by willrogers** [comment]
Basically, this is a very complicated thing to do with CS-Studio. What we do at Diamond is to launch CS-Studio in the background and open only small windows with the OPIs, but it is not trivial to set up the infrastructure for this.

It definitely won't be easy to change this, and if you have specific requirements you would be better following the development of Phoebus https://github.com/shroffk/phoebus which is the next generation of CS-Studio.
