### ISSUE TITLE
RAP GEF p2 site

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2556]
The rap gef url is a bit unusual. There seems to be a more standard one available:

```
-        <rap-gef-site>http://archive.eclipse.org/rt/rap/incubator/nightly/gef/20150327-1849</rap-gef-site>
+        <rap-gef-site>http://download.eclipse.org/rt/rap/incubator/3.0/gef/20150327-1849</rap-gef-site>
```

Could we swap?

@berryma4 @ralphlange

**Comment by ralphlange** [comment]
Sure. The time stamps are the same, and `3.0` sounds a bit more standard and stable than `nightly` - the advantage might be purely psychological, though.

**Comment by willrogers** [comment]
I'm pretty sure it's the same stuff and it will hang around, it's just that all the rest of our mirroring comes from `http://download.eclipse.org` so it's helpful to have this one as well.

**Comment by berryma4** [comment]
we have removed rap from the build, closing.
