### ISSUE TITLE
Outdated Download Link for SNS Version

### ISSUE THREAD

**Issue by pklaus** [ControlSystemStudio/cs-studio#2593]
The site-specific link for the CS-Studio edition at SNS found [on the CS-Studio Download page](http://controlsystemstudio.org/download.html)
should be corrected
from ~~<http://ics-web.sns.ornl.gov/css/index.html>~~
to <https://controlssoftware.sns.ornl.gov>.

**Comment by kasemir** [comment]
@berryma4  Eric, do you know how to update http://controlsystemstudio.org/download.html ?

**Comment by berryma4** [comment]
Updated:
https://github.com/ControlSystemStudio/controlsystemstudio.github.com/commit/7badf2caf2c9dbc1f7cf8b2704a5db2ee4f8e647
