### ISSUE TITLE
Phoebus application doesn't have p2 repo upload

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#2596]
Our build fails because of this.

**Comment by willrogers** [comment]
Similarly, because `org.csstudio.opibuilder` depends on `org.csstudio.phoebus.integration`, I don't think you can install opibuilder at all without the `org.phoebus.integration` feature.

**Comment by shroffk** [comment]
Sorry...I was planning on splitting up the plugins and features.
