### ISSUE TITLE
Phoebus find open port and app in path

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#2607]
I would like to have the integration plugin pick an open port, and find phoebus in the user path.

**Comment by shroffk** [comment]
Using the random port seems to not make much sense to me.
In that case it might be best to not use the ```-server``` options, so that each launch is a standalone instance of phoebus

**Comment by berryma4** [comment]
I was thinking one server instance (with port) per eclipse instance.

**Comment by shroffk** [comment]
I see...
Can I implement the following:
```
# launch the phoebus application with the -server argument, use a random available port
use_phoebus_server=true
```

This way, if my launcher script takes care of the port number then I can disable that by setting the above property to false

**Comment by berryma4** [comment]
My pull request you merged works. But, I'm combining two things, find
Phoebus in the user's path and pick an open port.

**Comment by shroffk** [comment]
I know, I have added on top of that

**Comment by shroffk** [comment]
https://github.com/ControlSystemStudio/cs-studio/pull/2610

**Comment by berryma4** [comment]
Thank you!
