### ISSUE TITLE
CS-Studio build improvements

### ISSUE THREAD

**Issue by shroffk** [ControlSystemStudio/cs-studio#2618]
During the developers meeting there were some concerns shared about the complexity of the build and the amount if time each build takes.

One potential idea to address this issue would be to merge the following repos into one.

- maven-osgi-bundles  
- cs-studio-thirdparty  
- cs-studio  
- org.csstudio.product.  

In my experience, these projects don't have an individual life cycle. They are very tightly coupled with each other, bringing them all together in a single build might reduce the time taken to fetch the artifact info for all the common p2 repos (eclipse, efxclipse, etc....) by eliminating the need to do so 4 times.

**Comment by shroffk** [comment]
https://github.com/ControlSystemStudio/cs-studio/tree/2618_restructured_repo
Here is the branch on which I have tried to restructure the repo as described in the issue ticket.
The new structure is as follows:

![image](https://user-images.githubusercontent.com/2111304/67019953-6f6db980-f0cb-11e9-8069-85048f6b35c2.png)


Pros:  
Building each module independently took me a total of around 59 mins...with the new repo the time came down to around 30 mins.

The poms are a lot cleaner now. The number of lines of pom.xml has greatly reduced since the common profiles, plugins, configurations, properties, repositories, etc...  are all in one master pom. This makes them easier to manage and maintain and easier to understand.

Cons:  
Sometimes the build fails, with similar errors as described in the jdk 11 build issue ticket. This might have nothing to do with the restructured repo itself...

I moved the other repo with the history...but we need to rewrite the history with the new paths.

@willrogers @css-iter ISIS other...

**Comment by willrogers** [comment]
@shroffk thanks for this, I expect it is an improvement.

I hope to get around to revisiting the CS-Studio build in a couple of weeks.

**Comment by ifmalcuaz** [comment]
cc @willrogers 

I am able to build it without errors on my machine at Diamond; how do you build a separate product?

**Comment by willrogers** [comment]
@shroffk how do you build the NSLS-II product with this structure?

**Comment by shroffk** [comment]
After completing the consolidated build of the complete cs-studio repo I build the nsls2 repo pointing to this build p2 repo

https://github.com/cs-studio-nsls2/org.csstudio.nsls2.product.git

```
mvn -DskipTests=true clean verify -Dcsstudio.composite.repo=${WORKSPACE}/p2repo
```

where `${WORKSPACE}/p2repo` is the p2repo from the above structure.

**Comment by shroffk** [comment]
@ifmalcuaz @willrogers how long did your build take?

**Comment by ifmalcuaz** [comment]
@shroffk applications took 35 minutes, the others a bit less

**Comment by shroffk** [comment]
So I would say that build improvement has generally been achieved.
Build times are now much lesser
Travis now builds & runs all unit tests
