### ISSUE TITLE
Show All/Hide All action in Databrowser

### ISSUE THREAD

**Issue by ifmalcuaz** [ControlSystemStudio/cs-studio#2625]
On the databrowser if you wanted to show or hide all the traces you need to individually click on the "Show" check boxes for each PV. It would be useful to have a Show/Hide All button somewhere; one suggestion is to just add two context menu actions when right clicking on the plot (Show All, Hide All, or similar):

![image](https://user-images.githubusercontent.com/43135998/73173844-33041d80-40fe-11ea-91ff-cc45168b19e4.png)

cc @willrogers

**Comment by willrogers** [comment]
@shroffk this was a user request

**Comment by kasemir** [comment]
Some of our users are in the habit of adding more and more items to a plot, then hide most of them because they're not really necessary, ..., and then complain that things slow down. Would a 'remove all' be more useful?

**Comment by shroffk** [comment]
Hmm... I have similar usage, where people add many traces (sometimes raw)... then hide most of them then and then wonder why databrowser uses so much memory.

> Would a 'remove all' be more useful?

If I understand the use case correctly, people still want to keep the traces in the properties but just not show/plot them.

I think we can add the show all/hide all actions since I don't think they make things worse...

In the future, when a trace is hidden we could have databrowser discard the retrieved archive data and pause the pv connection.

**Comment by Gir4ffe** [comment]
@willrogers asked me to elaborate on this. 

Currently we have some plt's setup that let us view an entire system. If I use our cooling water system as an example, there are many pv's over 4 chillers and associated equipment. 

When fault finding, it's really handy to be able to see everything together, to look for patterns/coincidences, also really handy to single one pv/ a few out. 

Having a select all would mean we could drill down and build up from one pv. Currently to do this we have to copy the pv's we want to a new plt and re-set the axis.

**Comment by willrogers** [comment]
Presumably, if I understand correctly, you could scroll through all the PVs and untick them rather than create a whole new plot? Not that I'm saying this is a good solution particularly.

**Comment by Gir4ffe** [comment]
You can indeed scroll through and tick/untick what you need. 

I have attached a screenshoot of pvs for the plt of 1 of our 4 chillers. As you can see, ticking and un-ticking takes a while :)  

![image](https://user-images.githubusercontent.com/60355612/73357530-75f7f980-4294-11ea-8ab8-2839ee4b9633.png)

**Comment by willrogers** [comment]
Thanks, I think that illustrates the problem.

**Comment by shroffk** [comment]
Thanks @Gir4ffe, your example clearly identifies your use case. 

Below I have described the workflow I have showed my users... 

I am guessing you are aware of the "edit selected items" 
![image](https://user-images.githubusercontent.com/2111304/73371559-d9c5f680-4283-11ea-817d-518baf438c1b.png)

"show"
![image](https://user-images.githubusercontent.com/2111304/73371640-f5c99800-4283-11ea-9b1c-fe4f7c0e5c65.png)

So it comes down to

Ctrl + a> "edit selected items" > check "show" > OK

So there is one extra step here compared to what you requested, but it is surely better than individually checking :)

**Comment by kasemir** [comment]
I'll add that "Edit Selected Items" support to the phoebus version, it hadn't been imported, yet.

**Comment by Gir4ffe** [comment]
@shroffk I was sort of aware - not had my official CSS training just yet (though I have had some)

Just had a go - works for me. 

Thanks very much @willrogers @shroffk @kasemir

**Comment by willrogers** [comment]
OK, let's close this one then.
