### ISSUE TITLE
The Absolute Time field in the Start/End Time widget in the Databrowser does not change the Start Time field

### ISSUE THREAD

**Issue by ifmalcuaz** [ControlSystemStudio/cs-studio#2630]
![image](https://user-images.githubusercontent.com/43135998/73466788-41f70400-437a-11ea-818b-6a59508889b5.png)
Pressing the -/+ buttons or editing the absolute time directly does not change the Start Time field, until a date is selected in the calendar widget above. (I.e. in the picture above, the Start Time should be set to 20H 01M 44S after typing, but it only does so when a date is selected from the calendar).

This is to do with the change from the 12H to 24H format. Though I am not sure if this is an Eclipse bug as the CalendarWidget code has not been changed for 5 years. The SelectionEvent does not fire for some reason in [CalendarWidget.java::168](https://github.com/ControlSystemStudio/cs-studio/blob/master/applications/apputil/apputil-plugins/org.csstudio.apputil.ui/src/org/csstudio/apputil/ui/time/CalendarWidget.java#L168).

cc @willrogers

**Comment by willrogers** [comment]
It looks like that was an Eclipse bug that has been fixed: https://bugs.eclipse.org/bugs/show_bug.cgi?id=550733
