### ISSUE TITLE
Data Browser: Allow 'drop' of PV names into plot on Linux

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#298]
On most OS, strings (PV names) can be dropped into the Data Browser plot, opening an "Add PV" dialog for the text, which is presumably a PV name.

On RedHat 6, no "drop" appears to be possible. Need to check drop types to determine why not.

**Comment by willrogers** [comment]
Shall we close this if it's not going to be fixed?

**Comment by kasemir** [comment]
OK
