### ISSUE TITLE
Data Browser some config not saved

### ISSUE THREAD

**Issue by tashasummers** [ControlSystemStudio/cs-studio#428]
In versions 3.1.6 and 3.2.12/13/15 when I save a data browser plot with area-type trace it reverts back to line plot when I relaunch the file. Similarly when I save a plot with an axis on the right side of the plot it goes back to the left side.

**Comment by kasemir** [comment]
The comprehensive data browser update #774 saves and restores all that can be configured.
There is now a little less that can be configured, but hopefully it "works" while before it was broken.
