### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by mdavidsaver** [ControlSystemStudio/cs-studio#535]
This is a minor issue I've seen this occasionally before.  Today I discovered a way to make it happen fairly repeatably in 3.2.15a.  The "progress" in question is data retrieval in Databrowser.  No associated exception on the console.  Hints on how to get more information are welcome.
# 

'Update Progress' has encountered a problem.

An internal error has occurred.

An internal error has occurred.
 Comparison method violates its general contract!

**Comment by berryma4** [comment]
is this fixed from #536

**Comment by willrogers** [comment]
I have never seen this problem.  I suggest we close unless someone can confirm in a recent release.

**Comment by mdavidsaver** [comment]
Fair enough.
