### ISSUE TITLE
BOY, mostly: Rethink Perspectives/Compact Mode/…, use Views for runtime (Lead: Kay - Reviewers: Kunal, Eric)

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#544]
Goal is to be able to “save” the layout of *.opi displays, so it can be “restored” and operators can switch between different layouts.
Maybe including a “frozen” mode where a “restored” layout cannot be altered.
Ideas (unclear if this is the solution):
OPI Runtime always based on “View”, and “Perspective” is used to save/restore.
Update compact mode to be more compact (hide status bar, …).

This should help with #457, #438, #101

**Comment by kasemir** [comment]
Notes from hangout today with FRIB, BNL, DLS, SESAME, ITER, SNS.

SNS:
See http://ics-web.sns.ornl.gov/kasemir/CSS_OPI_Views2.ppt.
All OPIRuntimes in RCP View.
Can use RCP Perspective to switch View arrangements.
Includes _all_ Views (Probe, Properties, ..).
Excludes partstack "org.eclipse.ui.editorss".

DLS:
All OPIRuntimes in top-level SWT Shell.
Running inside CSS, with usual context menu for PVs etc.
External tools can use --launcher.openFile to open these OPIRuntimes.
Since they're top-level shells, Linux/X11 tools can be used to locate them based on their window title and adjust their position.

SESAME:
See http://www.aps.anl.gov/epics/meetings/2014-10/presentations/Wednesday/Fall%202014%20EPICS%20Collaboration%20meeting_Ibrahim%20Saleh.pdf pages 12, 13.
All OPIRuntimes in standalone Eclipse Window, compact mode.
Compared to DLS, this adds the 'tab' for the single part within the window. Could display multiple tabs within a window, but don't really want to do that.
Added mechanism to load/save "Profiles": Iterates over all Shells in the workspace, identifies those which contain OPIRuntime, saves their *.opi path and macros. On restore, restores those that were saved and closed those which happen to be open but are not included in the saved profile.
Using CSS in "Development" or "Runtime" mode. Same CSS binary, but runtime mode closes/hides the main Eclipse workspace window, so end users only see the standalone Eclipse Windows with the compact-mode OPIRuntimes.

**Comment by willrogers** [comment]
Changes that are needed for OPI Shell:

* OpiShell.java
* OpenOpiShellAction.java
* Add OpenOpiShellAction in WidgetActionFactory.java
* Check for OPI_SHELL macro in OpenExternalDisplayAction.java - this allows us to open an OpiShell when calling --launcher.openFile
* Handle the OpiShell case in ScriptUtil.closeCurrentOPI()

Other changes we've made to o.c.o.opibuilder:

* Copy PV name from PV widget using middle-click (as in EDM)
* Update -share_link when running OPI against already-running CSS from command line (previously it updated only at CSS startup)

**Comment by willrogers** [comment]
And (for the record) I think runtime OPIs only in Views rather than Editors is a good idea.  It will make some of the non-EDM CSS work we're doing here much easier, because we would like to save custom perspectives and editors make it difficult.

Potentially making the editor stack more obvious is a good way to make this way of working intuitive.

**Comment by yazd** [comment]
As the screen share didn't go well yesterday, I created this gif to better explain what SESAME uses.

![window-profiles](https://cloud.githubusercontent.com/assets/1556354/5954857/b1ee604e-a7a5-11e4-87ef-ac863fe168b0.gif)

This shows how saving and loading a profile happens. It is also worth mentioning that the profiles are saved to a network file system, so that when the operators use a different computer, they still can access the profiles that they previously set.

**Comment by berryma4** [comment]
Okay, maybe I don't understand how the SESAME one works.  You are loading / saving profiles with a boy runtime screen?  Could you describe the layers in this ticket?

**Comment by berryma4** [comment]
I remember you said you were only looking at boy viewparts, but is it saved to an eclipse perspective or the whole thing is your own?

**Comment by yazd** [comment]
The whole thing is just two python scripts (one for saving and one for loading) and I believe it would work with upstream CSS as is.

What is done to save a profile is the following:
```
nwin = 0
workbench = display.getWidgetModel().getOpiRuntime().getSite().getWorkbenchWindow().getWorkbench()
for w in workbench.getWorkbenchWindows():
	e = w.getActivePage().getActiveEditor()
	if e.getClass().getName() == 'org.csstudio.opibuilder.runmode.OPIRunner':
		nwin = nwin + 1
		profile.write('[window' + str(nwin) + ']\n')
		profile.write('opi: ' + e.getOPIInput().getPath().toString() + '\n')
		profile.write('macros: ' + macro_rep(e.getOPIInput().getMacrosInput()) + '\n')
		profile.write('position: ' + str(w.getShell().getBounds().x) + ' ' + str(w.getShell().getBounds().y) + '\n')
		profile.write('\n')
````

As you see, it is as simple as it gets. The file produced is an ini-like file, which can be loaded by the other script.
The eclipse perspective format is not used.

**Comment by kasemir** [comment]
Notes from hangout today with FRIB, DLS, SESAME, ITER, SNS.

## Agreed upon with concrete initial steps for the next 1..2 weeks

Step 0: Be able to build again (#911)

Step 1: OPIRuntime in RCP View or SWT Shell
 * Not ‘Editor’. Merge boy_runtime_branch to remove OPIRuntime-in-Editor (1.1 – Kay)
 * ‘Shell’ = SWT Shell, not compact workbench window. Add DLS Shell support (1.2 - Will)
 * Actions support “Open” (using default),“Open in Workbench" (View), “Open in Standalone Window" (Shell), selectable via context menu or Ctrl/Shift-Click
 * Preference to select default = Workbench or Standalone
 

## Agreed upon, will do next

Add “Open in Editor”
 * .. for file resources as already done by DLS
 * .. for web resources via tmp file mechanism (org.csstudio.utility.file (?))

Add absolute/relative positioning for Shell
 * As in EDM, actions can open relative/absolute to button that contains the action

Option to start CSS with Workbench hidden
 * SESAME users initially only see the standalone OPIRuntimes
 * Workbench is minimized, so it shows in task bar, can be opened back up

## To be discussed later

Remove automated Perspective Switches
 * Data Browser Toolbar button
 * Opibuilder “Switch to OPI Runtime”
 * Remove “Open in LEFT”, … support of View        REVIEW AGAIN LATER

Add SESAME’s “Profile” window save/restore
 * Implemented in Java, locking the “profile” format and preference location of profile files
 * Yes, but: Is somewhat like perspectives. Could this be included in the perspective handling?DLS can still use Linux/X11 Windows arrangement. SESAME can still use scripts (publish them).

**Comment by willrogers** [comment]
The reason we use "Open in LEFT..." here at DLS is so that you can assign a button to open a new view and put it in the correct place.  This allows a more dynamic setup (e.g. all the motor screens go into the right stack and all the other OPIs go at the top).

**Comment by kasemir** [comment]
On the branch proj544_1.1_runtime_in_view, I've imported the key changes for the first step.

When opening a display runtime, that now executes in a "View", no matter if started from the "Top OPIs", an action, or the Navigator "Open With..".
The OPI Runtime perspective and the OPI Runtime view ID handling have been updated so that views can (again) be opened in designated "Left", "Right", .. part stack of the OPI Runtime view, fixing #142.
The data browser no longer automatically switches to its perspective from its toolbar button, because that messes you up when you have thought long and hard about your *.opi view arangement, and suddenly they're all switched with the perspective.
The old OPIRunner, i.e. the RCP 'editor' that executes the runtime, is still there and listed in the plugin.xml because this makes for a smoother transition when you open an existing workspace that had those open. It's meant to be removed when we're done with this.
The wording of the 'editor' contribution is now this:
`Navigator/Open With../OPI Display (Workspace)`: Opens runtime in View, i.e. this new default
`Navigator/Open With../OPI Display in legacy Editor`: Opens runtime in Editor, to be removed
`Navigator/Open With../OPI Editor: Opens in Editor`, to actually edit the *.opi file

I'm not sure I'd want to merge this into master, because right now this means you need to commit to using Views; we don't have the standalone Shell windows, yet.
Might be better to add your Runtime-in-Shell support and `Navigator/Open With../OPI Display (Standalone Window)`.
Finally we add a preference to select the default (Workbench, Shell?) and support Ctrl/Shift-Click to switch between them, and then merge it altogether.

**Comment by willrogers** [comment]
I can work on this now, but right now I'm figuring out how to build your branch, because our build only works for our branches.

**Comment by kasemir** [comment]
I build it as described in http://cs-studio.sourceforge.net/docbook/ch04.html .

I configure maven to use a local repository, i.e. I set <csstudio.local.repo> and not <csstudio.composite.repo>.

I build once with maven on the command line. The result is all the products, plus that local.repo directory now has all the plugins from CSS as well as dependencies, so it can be used as a target platform for the IDE.

Now I import the sources for the product and the cs-studio repo into the IDE to work on them. The required dependencies from maven-osgi-bundles, cs-studio-thirdparty and eclipse in general are found in the target platform (local.repo).

**Comment by kasemir** [comment]
Just merged the latest from 'master' into  the proj544_1.1_runtime_in_view branch so we don't diverge too much.

What works, for example starting with the 'BOY Examples' main.opi:
 * In Navigator, right-click on *.opi to "Open With../OPI Display (Standalone Window)" to open in Shell
 * In Navigator, right-click on *.opi to "Open With../OPI Display (Workbench)" to open in View, within the workbench, with all the fluff
 * When opened in View, one can operate action buttons to open further displays, and go 'back' to the previous one.

What's not quite right:
 * When right-clicking on an action button, you get the old choices "Open in new Tab" (i.e. new View), "Open in new Window" (new View in new Workbench window).
 * When in the standalone Shell, you can't operate any action buttons to open different displays because of some null ptr error.

What I think would be good to choices when right-clicking on an action that opens runtimes:
 * "Open": Opens in the current view or shell, replacing its current content.
 * "Open in Workbench": Opens the display in a new View. Should this be disabled when in a standalone shell?
 * "Open in Standalone Window": Opens in new standalone Shell.
We drop the existing "Open in new Window" which opens a View in a new workbench window. If people want a new workbench window, they can get that via Window/New Window, then move Views between the workbench windows.

Under the hood, the action needs the following options to configure what happens if the user simply 'clicks' on the action without right-click-and-pick-a-specific-mode:
1) Default: Uses Open=Replace or View or Shell as configured in a preference setting
2) View
3) Shell

Who's available on Monday, 23-March, for a hangout on this?

**Comment by berryma4** [comment]
I'm in

**Comment by kasemir** [comment]
Hangout today w/ Kunal, DLS, Eric, notes in https://docs.google.com/document/d/1ZO6HwDVRQqmhvfoD5ELDCqXB-k_G1qgcfFYn85qa8sE/edit?usp=sharing

DLS will fix action button issues (still shows old menus, actions don't work when running in shell).

Meet again April 7.

**Comment by willrogers** [comment]
I've put a proposal at the bottom of that document.

I'll try to pull together a working version of that proposal to put on the development branch - it shouldn't take long.

**Comment by kasemir** [comment]
Very good, I like how you thought about allowing the 'action' to go from a Shell back to a view in (new or existing) workbench!

**Comment by willrogers** [comment]
I am not sure what to do about opening views in different workbench locations.  It seems that you need a particular perspective in order to do this.  However, this isn't the desired behaviour so much as the constraints of the platform.

To be clear, the beamline people at Diamond (they're not using OPI shells) would like the ability to open an OPI in a particular location when pressing a button.

**Comment by kasemir** [comment]
Yes, to support opening views in desired location there's no change:
You need to be in the "OPI Runtime" perspective, or a customized one that is based on it.

**Comment by willrogers** [comment]
Could we add the placeholders to all cs-studio perspectives?

(and unrelated)

If you save a perspective starting with OPI runtime and give it a different name, will this still work?

**Comment by kasemir** [comment]
Yes, that would help.
But unclear how to do that.
Would be nice to re-use the OPIPerspective code, but don't want to add dependencies to org.cstudio.opibuilder to data browser, scan, alarm, ..

(really related)

Yes, that still works.

**Comment by willrogers** [comment]
Maybe this is not so bad.  

* Only the designer of an OPI gets to choose where the next OPI is placed.
* This only really makes sense within the context of a perspective.  If the OPI is used elsewhere, continuing to try to place the next OPI makes less sense.
* The designer can base the perspective on OPI Runtime or (if advanced) use the same placeholders programmatically.
* I don't think the user can find out where the OPI is supposed to open.
* If the user rearranges the perspective, the OPI should still open in the correct stack, even if that has been moved.

So I suggest:

* Only have the 'Position' option available when 'Target' is 'New Tab'.  Possibly add a little warning at create time.
* Remove the perspective check.  If the placeholders can't be found, the OPI will open wherever it would have otherwise, in a new tab.

What do you think?

**Comment by kasemir** [comment]
Kay needs to Iook at the OpenOPIInView action, see if that's superfluous.
Kay will also continue to merge from master as it's re-organized to keep this branch up to date.

When opening an OPI that wants to be "left", but there is no "left" because not in OPIRuntime-type perspective
-> Kay: Ignore, open in default location, instead of bothering user with "Do you want to switch to OPIBuilder Perspective".

Perspectives: "OPIRuntime" is the only one which provides placeholders "left", "right", "top", "bottom".
Don't: DataBrowser, Scan, …perspectives derive from OPIRuntime, because that adds dependencies.
Possible: Add "Left", .. placeholders in DataBrowserPerspective etc. simply by using that same name.
How to share custom, user-created saved/named perspectives?
Kunal's product: Preference setting to list content of initial default perspective.
--> Have preferences that allow us to define multiple perspectives? Add utility that converts a saved perspective into the preference string that can be added to another product, making that saved perspective available in other products?
Will to check how perspectives are saved, how we could parse that information to eventually use it for preferences that are added in other product.

**Comment by kasemir** [comment]
Finally got around to look at this. Removed the OpenOPIInView and the AbstractOpenOPIAction, leaving just OpenDisplayAction for all cases.

Want to clean the updated OpenDisplayAction up by merging the 'Position' and 'Target' properties.
'Target' is from OpenRelatedDisplayAction, has default, new workbench tab, new workbench window, new standalone window.
'Position' is from OPIRunnerPerspective, applies only to Views in OPIRuntime perspective or derived perspectives, with values left, right, detached, ..

Experimenting with one "Mode" that describes how to open a new OPI, with options:
Replace current (view or shell), New Tab (view), New Left Tab, New Right Tab, New Top Tab, New Bottom Tab, New Detached Tab, New Workbench Window, New Standalone Window (shell).

Key modifiers would still override: Ctrl -> New Tab, Shift -> new workbench window, Ctrl+Shift: New Shell.

**Comment by willrogers** [comment]
This now looks very good to me.  There's one inconsistency still, which is that if you use the 'Replace' target from within a shell, the old window doesn't disappear.  I think logically that the old window should be removed.

I've got a commit to do this but it needs tidying up a bit before I can push it on to the branch.  I'll try to do that tomorrow.

**Comment by kasemir** [comment]
I agree that it's come along.

When Will added the Standalone Window (runtime in shell), he commented on the OpenOPIInView action, and that had indeed become convoluted..

I combined the AbstractOpenOPIAction + OpenOPIInView + OpenDisplayAction into just an OpenDisplayAction.

Then updated the RunModeService to have only 2 calls for opening stuff, consolidating the original OpenDisplayAction.PROP_REPLACE and OpenOPIInView.PROP_POSITION into one RunModeService.DisplayMode.

OpenDisplayAction has comments on how it parses older files, resulting in the same behavior for files I tried. For what it's worth, when Will consolidated the OpenDisplayTarget, DEFAULT=replace-current and NEW_TAB were swapped. Fixed that, so BOY example 4_Actions1.opi works as before.

RunModeService handled one very specific use case of the OPI editor, which wants to use a designated  workbench window for executing displays when pushing "Run" in the editor. Since this only concerns the editor, I moved into to the editor's RunOPIAction.

I just removed OPIRunner, i.e. the "Editor" that executes runtime, so runtimes are now _only_ in View or Shell.

DataBrowser no longer automatically switches to its perspective when opened from toolbar.
Opibuilder no longer nags "Do you want to switch to the OPI Runtime perspective?".
--> All arrangements left to user.

Will, if you can tweak the RunModeService so that on 'replace' for an OPIShell it closes the old one, that'll be great.

I'll schedule a hangout early next week, possible topics:

Sesame scripts to save/restore window arrangement: Might need porting for changed RunModeService.

Create perspectives from preferences, or somehow else allow installing a perspective arrangement?

Add 'Open in Editor' context menu to runtime as done by DLS. If the runtime has a file name, it'll open that in the editor. For web resouces, look at tmp file mechanism from org.csstudio.utility.file.

Preference to hide the shell support.

Add absolute/relative positioning for Shell, as in EDM, where displays can open relative/absolute to button that contains the action.

**Comment by kasemir** [comment]
On the master branch, `opibuilder` has just been modularized. `*opibuilder*` plugins and features moved into their own `cs-studio/applications/opibuilder/*` subdirs.
Will mentioned one more thing he'll fix on Monday in #1066.
Then I'll merge the directory rearrangement from master into proj544_1.1_runtime_in_view to stay aligned with the master branch.

**Comment by kasemir** [comment]
Kay will merge master into proj. branch.

Will looked at Perspectives:
Stored in E4 appliction model *.xmi file.
Not obvious how to extract just the perspective info.
Might need to open MWindow instead of SWT shell in order to see Shell in application window.

DLS will add 'Open in Editor' context menu after master & proj. branch have been synced.

Don't pursue hiding the shell support for now, unless we find it's actually required by some sites.

Eric may have somebody to try CSS build from the proj. branch.

Timeline:
Close 4.1 by end of month, which handles the application restructuring.
On the way, each time master has been updated with a restructured module, merge master into proj branch.
4.2 could include the shell/view update.

**Comment by kasemir** [comment]
master has been merged into the proj544_1.1_runtime_in_view  branch. Needed to update *rap* plugin to use Java 8.

**Comment by willrogers** [comment]
I've added the option to edit OPI to the right-click menu on the branch proj544_1.1_runtime_in_view.  Please try and see what you find.  In particular, it's a bit tricky to test the http OPIs, so see what happens if you try to edit.

**Comment by willrogers** [comment]
I've now also changed OPIShell to launch in the absolute position specified in the OPI file.

Relative positioning is a possible addition.

**Comment by pavel-ch** [comment]
Hello Will,
sorry for stepping into your discussion. I am tracking the CS/Studio for some time, hoping for its use in my future project.  The impossibility of fixed and relative window positions is one of reasons which prevented me to use the CSS (or BOY in particular) so far. It is very positive seeing that you are addressing exactly this now. However, using the absolute position specified in the OPI file seems to me being very unflexible.
See my comment in [#101](https://github.com/ControlSystemStudio/cs-studio/issues/101) thread on 3 Nov 2013(!), with a hope being some inspiration for you.
Thank you. Pavel

**Comment by willrogers** [comment]
Hi Pavel,

This is a reasonable feature request.  It's not trivial to add (the OPI shell positioning from value in OPI file was trivial) but it will go on the list of possible requirements.

Cheers,
Will

**Comment by berryma4** [comment]
Just wondering,  'Open in Editor' ....
If a person opens in editor and the opi screen location is a url, does this grab everything? ie. images, linking containers, scripts?

**Comment by willrogers** [comment]
It's currently (in theory) disabled if it's a URL.  Although we can't test this very easily from here.

**Comment by kasemir** [comment]
What I'd like it to do is open the 'original file'. When that file is behind a http link, maybe we can add support for getting that stream downloaded into a local file, but then I'd only expect that to be the one file. So I can look at it, edit, but it may not "work" because links that were fine relative to the URL would now get resolved relative to the local file and thus remain unresolved.
I don't think it's necessary to add logic that will try to understand the file & download all the links as well, because when you do that with the 'top level' URL-linked display of a site, you'd end up with something that would be almost as bad as Maven.

**Comment by willrogers** [comment]
How do you think unresolved links should work?

At present, unless I have something unusual about my build, BOY won't open OPIs with unresolved linking containers, either in run time or in an editor.  EDM just has a blank space, which I think works just fine.

Otherwise, curiously enough, if I make an HTTP OPI a `RunnerInput` then editing works just fine.

**Comment by willrogers** [comment]
Re: perspectives.  In previous versions of Eclipse (3.x) you could save your preferences into an `.epf.` file.  It turns out that a perspective is stored as escaped XML in one line of the `.epf` file.  You can't export perspectives separately to the other preferences, as far as I can tell.

[This bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=378811) claims that this functionality will be restored in Mars M7, although I don't know whether to believe that or not.  Potentially this would at least allow us to 'hook into' some existing functionality, rather than create it all for ourselves.

Of course, it would ignore OPI shells.  We might then want to have buttons that save / restore windows, and at the same time save / offer to restore the perspective being used when saved.

**Comment by willrogers** [comment]
More generally, how long do you think we should keep this ticket / branch open?  I think we have reached a self-consistent set of features now, even though we haven't addressed the perspectives mentioned in the title yet...

**Comment by kasemir** [comment]
Re Linking containers, they are by now broken every way. A linking container should basically just be the name of the linked file. At runtime, the container widget then tries to load the file as a sub-model.
Linked content not available at edit time -> No problem at all.
Linked content not available at run time -> Should have empty spare there as you suggest.

Instead, the linked content has always been somehow merged into the main model. Since #912 #913 with numerous 'if (widget instanceof Linking*)' checks and a rising number of bugs #977, #998, #1052, #1081. I see linking containers as a major bug/misdesign in the current opibuilder.

As for perspectives, I think that's the missing item for closing this project.
Your info about possible changes to the *.epf file and perspectives is interesting.
I had also looked at how the code-based perspectives turn into model-based perspectives at runtime, thinking that maybe we'll have to end up with our own way use File/Export and Import to write/save our own type of perspective files, which are really view stack info plus *opi parts each with input & macros.

**Comment by willrogers** [comment]
I added the middle-click copy to this branch.  I also merged master into this branch again.  

I am not entirely sure what the behaviour will be on Windows but I expect that middle-click just won't paste.  Please go ahead and try to see what you think.

**Comment by kasemir** [comment]
I tried the middle click. It works OK on Linux when I middle-click to copy, then middle-click someplace else to paste. But it's not the same as the Context menu for Process Variable/Copy PV to clipboard.
With copy to clipboard, a Ctrl-V or Context menu/Paste will paste the PV.

I compared org.csstudio.csdata.clipboard/CopyPvToClipboard with the new Middle-button support in org.csstudio.opibuilder.runmode.RuntimePatchedSelectionTool.
One difference is that the older CopyPvToClipboard failed to dispose the clipboard, I just fixed that.

Then there are two ways of sending the PV name to the clipboard:

```
// Copies to middle button paste buffer,
// to be pasted via another middle-button click
clipboard.setContents(new Object[] { pvName },
            new Transfer[] { TextTransfer.getInstance() },
            DND.SELECTION_CLIPBOARD);

// Copies to normal clipboard,
// to be pasted via Ctrl-V or Edit/Paste
clipboard.setContents(new String[] { pvName },
            new Transfer[] { TextTransfer.getInstance() });
```

Would it make sense to do both for the middle-button-copy?
So the PV name can then be pasted via Ctrl-V as well as middle-button-click?

**Comment by willrogers** [comment]
I don't mind.  I don't expect anyone wants to use two clipboards for different things at the same time. 

I'm happy to leave your change and then it's there for Windows users as well.

**Comment by kasemir** [comment]
Status update.. I've fixed bugs in the basic handling of views and how they remember their input (path to display, macro). 


How to create a new display layout
----------------------------------

1. Open fresh "OPI Runtime" perspective: Window/Open Perspective/Other/OPI Runtime. "Reset" if it was already active.
2. Open views, position them as desired.
3. Invoke "Save As" context menu on the perspective.

You can now close the perspective, later re-open it, or switch between perspectives.

After closing or moving views, either
a) "Reset" the perspective to revert to the original layout
b) Use "Save As" with a new name for a new perspective, or under the same name to overwrite the existing perspective.

The OPI Runtime context menu option to switch to the "OPI Runtime Perspective" has been removed. It would direct the user back to an empty perspective.

### Layout of the "OPI Runtime" Perspective

The OPI Runtime perspective has part stacks named CENTER, TOP, BOTTOM, LEFT, RIGHT which are
positioned as one would guess.
When an action is configured to open an *.opi to the "left", it will be placed in the LEFT part stack.

When these part stacks are empty, they are invisible and it is thus impossible to manually move displays
into them. A display can be positioned "left" from the center, but the actual LEFT part stack would be
even further to the left.

The preference option to "Show OPI Runtime Stacks" adds one placeholder view in each part stack,
which helps positioning views in those stacks.
Remember, however, to close the placeholder views when done!


### Association of View to their input

Views track their current input (path to *.opi, macros) in the RCP 'Memento',
which is part of the 'persisted state' of the underlying E4 model.
Perspectives track the IDs and positions of their views,
and each view obtains its input from its memento.

This works perfectly for allowing to restore the last known state of the workbench
after a CS-Studio restart. When opening a previously closed perspective, its
views and their location are restored as well, but note that this will use the last
known input for each view.

Example:
Create a new perspective, place 'main.opi' in center, save as MAIN perspective, close perspective.

Open MAIN perspective: Restored as saved.

Open MAIN perspective, close 'main.opi', 'Reset' perspective: Restored as saved.

Open MAIN perspective, use an action button in 'main.opi' to navigate to 'subsystem.opi': From now on, the MAIN perspective will show 'subsystem.opi' in the center, because the perspective tracks the view, and the view then tracks its most recent input.

There is at this time no way to define an "original" input, to prevent the OPI View from saving changes to its input that result from navigating to other displays.


### Multiple Windows

If you want displays to be outside of the original workbench window, there are three options:

1) 'Detach' by dragging it outside of the workbench.
   Detached windows belong to the current perspective of their origin window.
   They open/close with perspective changes.
   
2) Open display in new workbench (or move to another existing workbench).
   Each workbench has its own perspective.

3) Standalone Window (shell)
   Not part of any perspective, will not be persisted over application restarts.
   
   
### Snapshot, Restore complete Workbench

We don't have a nice way to save a selected perspective so that it could be added to another CS-Studio instance, for example to prepare perspectives for a beam line.
Will's comment from April 28 points to a bug report which shows activity, but it's not solved.

Meanwhile, we know that the workspace file
   
    .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi

contains the definition of all perspectives (with list of their view) and views (with their memento for *.opi path and macros).

While CS-Studio is _not_ running, you can copy that file, then either restore it later to reset a desired workbench setup,
or place it in the workspace of another CS-Studio instance, which is also not running at that time, to duplicate the
workbench setup.

**Comment by kasemir** [comment]
Snapshot of the OPI Runtime perspective when "Show OPI Runtime Stacks" preference is set:

![placeholders](https://cloud.githubusercontent.com/assets/1932421/7960315/aec3918e-09cd-11e5-9ce8-9c3618cd7bd4.png)

**Comment by willrogers** [comment]
This commit https://github.com/ControlSystemStudio/cs-studio/commit/ef5dd189b6b6b33c257396cb0f08cd1c0c26d043 adds "Edit OPI" context menu item.  I see it whether right-clicking in a view or a standalone window.  I don't know why you don't see it @kasemir.

![2015-06-03 17 43 44](https://cloud.githubusercontent.com/assets/2440055/7965867/284d464a-0a18-11e5-8b00-5dc01a42d00a.jpg)

**Comment by kasemir** [comment]
Ah, I didn't see it because my displays are loaded from http:// links.
Works fine for local files.

**Comment by berryma4** [comment]
Is there an error, or popup if it http?  I'm just wondering what happens
and how graceful.

**Comment by willrogers** [comment]
The menu item just isn't there if it's an http opi.

You could argue that it would be better for the option to be greyed out.

**Comment by berryma4** [comment]
Yes, greyed out sounds good, but not being there is too.  Thank you!

**Comment by willrogers** [comment]
I pushed one more commit.  This makes the cursor change to a red cross if it is hovering over a PV widget whose PV is read-only (as suggested by @kasemir).  Please give it a try and see if it works well for you.

I am away for three weeks from Monday.  I'm happy for this branch to be merged once 4.1 is released.  If you've got any comments for me to look at, ask sooner rather than later!  You can of course just revert any commits that you don't want if necessary.

**Comment by kasemir** [comment]
Thanks for the read-only cursor!

**Comment by willrogers** [comment]
In investigating some funny behaviour with my previous commit, I found that what we want already exists.  However, it doesn't work for widgets that are read-only //when the screen is launched//, which loses a lot of the benefit.

The commit you can see above (https://github.com/dls-controls/cs-studio/commit/abf6f49aadfcfbb838a827bec158c5aa12d756a5) is one way to correct the original behaviour, although it changes an interface.  I think this should be reviewed before being accepted.

I've reverted my original commit.

**Comment by kasemir** [comment]
I think the interface change is OK because widgets use the AbstractPVWidgetEditPart.java anyway. If it turns into a problem with very few widgets that directly implement IPVWidgetEditpart.java, best fix those. If all fails, add a default implementation to the interface, now that we have Java 8 as a requirement anyway.

**Comment by willrogers** [comment]
OK, I've pushed this change.  If I find a better way to do it in future we can revisit it.

**Comment by willrogers** [comment]
OK, I've merged that last feature into this feature branch.  I now believe that the `proj544_1.1_runtime_in_view` branch has a consistent set of features and I'm very keen to merge it into `master`, not because I believe it's perfect but because I think we'll get more feedback once it's on master and more people can see it.

I'm happy to address anything with this branch if anyone feels it's not ready to merge.

This branch does not have saving and sharing of perspectives, but I think that should now go into a new ticket and a new feature branch.

**Comment by willrogers** [comment]
In #1303 @utzeln mentions that the option to open an OPI in a new window is lost (I think this means when right-clicking from the Navigator).  The relevant comment in this thread is on 20th March, from @kasemir:

> What I think would be good to choices when right-clicking on an action that opens runtimes:
> 
> * "Open": Opens in the current view or shell, replacing its current content.
> * "Open in Workbench": Opens the display in a new View. Should this be disabled when in a standalone shell?
> * "Open in Standalone Window": Opens in new standalone Shell. We drop the existing "Open in new Window" which opens a View in a new workbench window. If people want a new workbench window, they can get that via Window/New Window, then move Views between the workbench windows.

It may be that this is the wrong decision and we should add back the New Window option.

**Comment by kasemir** [comment]
What you cite above is about actions. For action buttons, we have these options in the context menu:
* Open: Does what the action says, by default "replace current display"
* Open in Workbench Tab: Opens as a new view in the same workbench window
* Open in new Workbench: .. new view in new workbench window
* Open in standalone window: The EDM-type top level shell that lacks some features, where we are discussing making this an optional feature

In the navigator, we have 
* OPI Display (Workbench): Same as the "Open in workbench Tab"
* OPI Display (Standalone Window): Same as "Open in standalone window" (EDM-type shell, should become optional)
* OPI Editor: Editor

So in here you'd like to add "Open in new Workbench"?
Then note #1329: That's really a new window, can't drag between them.

**Comment by willrogers** [comment]
This is a requirement from ITER, not Diamond!  @utzeln

**Comment by berryma4** [comment]
I thought I would mention that there seems to be some action on the eclipse bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=378811

**Comment by willrogers** [comment]
I've opened #1398 to look at the perspectives part of this.  May I close this ticket?
