### ISSUE TITLE
Graph lines not matching data in databrowser

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#598]
![databrowser](https://cloud.githubusercontent.com/assets/854021/3721624/20333b86-1662-11e4-8a80-6477b0814662.png)
![databrowser1](https://cloud.githubusercontent.com/assets/854021/3721625/217fd53a-1662-11e4-8c95-33847110be81.png)

**Comment by kasemir** [comment]
Does this still happen with the updated data browser, #774 ?
