### ISSUE TITLE
BOY Symbol widgets should support SVG animation

### ISSUE THREAD

**Issue by utzeln** [ControlSystemStudio/cs-studio#599]
To display SVG image files, Apache™ Batik SVG Java-based Toolkit is currently used by the BOY Symbol Widgets.

The latest revision of Batik, release 1.7 supports a nearly complete implementation of declarative SVG animation.

Example of svg xml code for a square rotating about its centre:
```<rect x="150" y="20" width="60" height="60" fill="blue">
  <animateTransform attributeType="xml"
                    attributeName="transform"
                    type="rotate"
                    from="0 180 50"
                    to="360 180 50"
                    "begin="3s" dur="6s"
                    repeatCount="indefinite"/>
</rect>```

ITER Use Case:
In case of a valve opening/closing, an animated SVG file that displays the valve in its open then close position alternatively at 2Hz frequency has to be supported.

**Comment by arnaudf-iter** [comment]
Added ```o.c.utility.batik.SVGHandler``` to handle both static & animated SVGs + updated ```o.c.swt.widgets.symbol.SVGSymbolImage``` to use it.

Some bugs in Batik framework dependencies have been fixed by Jaka adding 2 new fragments:
- ```org.csstudio.batik.dom.fragment_1.0.0.jar```
- ```org.csstudio.batik.dom.svg.fragment_1.0.0.jar```
