### ISSUE TITLE
"PVUtil" is not defined since JavaScript support update

### ISSUE THREAD

**Issue by kasemir** [ControlSystemStudio/cs-studio#723]
After #528 updated the JavaScript support, I get errors as soon as *.opi files use scripts.
For example, I build and run `org.csstudio.product`, install the BOY examples, open `main.opi`, then "Startup", then "See All Widgets":
```
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: ReferenceError: "PVUtil" is not defined. (<Unknown Source>#2) in <Unknown Source> at line number 2
```

**Comment by berryma4** [comment]
I believe this can be closed?

**Comment by kasemir** [comment]
Do javascripts now work when using the script engine in the jdk, or do we still need to use our own bundled rhino?
