### ISSUE TITLE
databrowser display labels not matching

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#755]
From user:

I just went through half of the list of traces and changed all display names from "****DGW" to something more meaningful. I saved the plt and closed CSS. When I opened CSS again, I noticed that the color assignment and the display names were mixed up (I have no earlier screenshot, so I can't proof that). Also, when opening the properties window, I don't see the display labels I entered anymore! In the screenshot you can compare the "Display Name" column with the legend below the graph. When I hide the trace and bring it back the legend updates to the Display Name shown in the properties list. The same happens to color assignments. Notice the cyan tick curve with the dip? This is I214DGW and should be orange. I took two more screenshots that show the color change (and also line width) as I hide and bring back this trace. All I did between the three screen shots is hide and bring back a few traces.

![1](https://cloud.githubusercontent.com/assets/854021/4617410/8d1fbc00-52fe-11e4-845d-9b44bb86e0ec.png)

![2](https://cloud.githubusercontent.com/assets/854021/4617415/90583474-52fe-11e4-82f4-81166b01d7e3.png)

![3](https://cloud.githubusercontent.com/assets/854021/4617417/92845db8-52fe-11e4-89d4-63a2003c575d.png)

**Comment by kasemir** [comment]
The color assignment issue resulted from the older databrowser saving the color twice:
Once for the channel, once as part of the XYGraphSettings, but the two weren't synced.
Trace "1" in one could become trace "3" in the other, and the colors etc. got all messed up.
Should be fixed with #774
