### ISSUE TITLE
Allow Data Browser to show standard deviation instead of min-max for archive data

### ISSUE THREAD

**Issue by willrogers** [ControlSystemStudio/cs-studio#764]
At Diamond we had a summer student integrating an archiver with Data Browser.

One requirement from the old program was to show standard deviation of 'decimated' data, as well as max and min values which are already shown in the Data Browser.  The ArchiveVStatistics type already has the capability to store this information; the Data Browser just needs to show it.

We've got a branch which allows selection between the two options, using the 'Edit Item' dialog:
![screenshot-edit item](https://cloud.githubusercontent.com/assets/2440055/4677279/58a824b4-55e5-11e4-869a-2889f14b1dc7.png)

Is this something you would accept in Data Browser?  I'll open a pull request with the branch.

**Comment by berryma4** [comment]
can I close this?

**Comment by kasemir** [comment]
I think the basics of allowing the data browser to display stddev is there.
It is up to the data source to provide it VStatistics samples which contain stddev > 0.

**Comment by willrogers** [comment]
We can test this as of today, so give us a couple of days to give it a go.

Or close it and we can open new tickets if you prefer.
