### ISSUE TITLE
Unit test cleanup (Lead: Eric - Reviewers: ESS)

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#766]
After #462

**Comment by shroffk** [comment]
https://github.com/ControlSystemStudio/cs-studio/wiki/UnitTests

**Comment by shroffk** [comment]
For junit, it seems maven run as unit tests classes named either *Test or Test*
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running tests.example.AppTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running tests.example.TestApp
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

**Comment by shroffk** [comment]
For the Naming Convention for I propose the following:
(the aim is to be able to use maven goals to select the appropriate tests to run)

1. Plain JUnit tests: *[[Test]].java

2. JUnit Plug-in tests that need the Eclipse runtime but no GUI: *[[eclipseIT]].java
We can use tycho-surefire plugin configured to include all *eclipseIT.java http://www.eclipse.org/tycho/sitedocs/tycho-surefire/tycho-surefire-plugin/test-mojo.html
This way we are also compatible with the maven surefire 
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html

3. JUnit Plug-in tests that need the runtime and the GUI: *[[UiIT]].java ?

4. A demo that requires user input or other interaction. Not a real test, but happens to be implemented with JUnit: *Demo.java

In all 4 cases if you use right click -> Run as -> Run Junit Test to run all test cases

**Comment by willrogers** [comment]
Fine by me.

**Comment by willrogers** [comment]
We are now running unit tests in Jenkins.  The last run had 536 tests in applications and 59 tests in core, of which about 20% failed.  I don't know how well this corresponds to the tests that exist, but it certainly seems like a good start.

**Comment by berryma4** [comment]
https://docs.google.com/document/d/1Edji59EmGca04QEFYX0qiAmxBrMXqunsHypSyMBPzjo/edit#heading=h.6mdsxfux2rh3

**Comment by willrogers** [comment]
`org.csstudio.vtype.pv.test` has some files that require a soft IOC.  I renamed them to `*IT.java`, but reading this ticket perhaps I should call them `*Demo.java`. Is that correct? @shroffk @kasemir @berryma4

**Comment by berryma4** [comment]
Your right, adding an IOC as a requirement for the test "sounds" like an integration test.  I guess the issue is how you are running the IOC for the IT.  If you start it up from Eclipse, then it's an IT.  If if requires a person to start the IOC, then it's a Demo.

**Comment by willrogers** [comment]
Wiki page updated: https://github.com/ControlSystemStudio/cs-studio/wiki/UnitTests

**Comment by willrogers** [comment]
All unit tests now passing!

**Comment by berryma4** [comment]
![image](https://cloud.githubusercontent.com/assets/854021/14330280/e0085792-fc0d-11e5-9c27-80c4d75ec058.png)

**Comment by berryma4** [comment]
![image](https://cloud.githubusercontent.com/assets/854021/14355735/0d090b86-fcb0-11e5-94ba-e6f6a98c4968.png)
