### ISSUE TITLE
OutOfMemory error: LinearScaleTicksLabel (xygraph: zoom in)

### ISSUE THREAD

**Issue by DjThunder** [ControlSystemStudio/cs-studio#775]
I have a huge problem on xygraph, when using zoom function with mouse:
* OutOfMemory error when zooming in

No problem with zoom out.

I really do not understand what could be the problem with LinearScaleTicksLabel ArrayList... (which is trying to grow the list).

Note: Graph can be empty or not, doesn't matter

**Comment by kasemir** [comment]
Has this been fixed while fixing #737 ?

**Comment by berryma4** [comment]
closing unless this reappears.
