### ISSUE TITLE
ImageBoolIndicator returns null pointer

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#778]
@shroffk 
@kasemir 

So, it seems there is an issue:
ImageBoolIndicatorEditpart:73 returns a null pointer 

This may be related to #580

I haven't been able to look into this much, but I get this error whenever you try to open an opi with a ImageBoolIndicator, or try to drag and drop one in an editor.

**Comment by jbobnar** [comment]
This issue has been fixed by #837 and should be closed.
