### ISSUE TITLE
Java 8 development branch (Lead: Kunal - Reviewers: Gabriele)

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#799]

**Comment by shroffk** [comment]
Use of Instant and Period
Integration of JavaFX

**Comment by shroffk** [comment]
TODO:
-use a released verison of e(fx)clipse instead of the nightly releases
-the pom files need to be updated to include the p2 repo hosting the efx plugins
-include the required features in the products to ensure that logging.ui works with the javafxviews

**Comment by shroffk** [comment]
All TODOs: 
Merged to Master
