### ISSUE TITLE
Prototype for SWT widget full integration in CSStudio/BOY

### ISSUE THREAD

**Issue by gcarcassi** [ControlSystemStudio/cs-studio#80]
Given that we still have no consensus on how a general purpose widget should be integrated, and that BNL still have to release them, I'll take the VTable widget as the prototype for how things will be integrated in the future. If anybody is interested in using widget coming from BNL (including graphene) please review and make sure things work for you.

Border
Currently there is no standard alarm based border. There is BOY, which is only accessible if BOY itself manages the connection. The current border does not handle the UNDEFINED alarm.
Current proposal is:
* Define in org.epics.vtype some utility class that returns the color values for alarm conditions. This way any visual element can use it.
* Create a border class in org.csstudio.utility.pvmanager.widgets. Which has a setAlarm method which uses the previous class to get the color
* Have widgets use the border. It is not clear whether it's the widget itself that has the border, or it should be hooked up from outside. Need to explore both options and see what's better
Eric brought up the subject of accessibility. The border may also display text (if SWT allows, no idea). We could have a CSStudio wide flag that decides whether to just display the color, the text or both.

Scripting
My understanding is that scripting is single threaded, can bring CSStudio down, and sites general frown upon it. I don't have a good understanding how this can be integrated properly. Current proposal is not to actively support it. Whatever works works at your own risk.

Web OPI
While I don't think there is anything to block this, BNL does not have the manpower to test and support this. If any other site wants to contribute here, let me know!

Notification
We have experimented with a couple of different way to broadcast selections through pvs. This works well, and it has the potential to eliminate the need for scripting in many cases. We need to formalize an approach so that it can be replicated consistently. The two main competing approaches are:
* Widget receives the pv on which to notify. The widget itself does the connection. This is simpler to the potential user, but less flexible.
* Widget provides a javabean notification mechanism. The BOY layer takes care of creating the listener and attaching it a pv given by the user. More flexible but more cumbersome to implement (widget has to implement the listener, BOY layer needs to hook it up)
If the second can be made decent through pre-canned listeners and utilities, will use the second. Otherwise the first.

Error notification
We need to define a consistent way for error notifications. There are two different types: read errors and write errors. Read errors should be more prominent. We currently have the error bar, which is too big for "small" widgets (like a text field). We could have the error bar not display the error, so that only the icon shows. The icon would be clickable to get the message and the stack trace. This way all widgets could use the error bar and, depending on the size of the widget, one can decide whether it wants the icon only or also the text message.
Write errors are of two kinds:
* I can't write (no privilege, pv is not writeable, expression is read only, ...) This would result also in a isWriteConnected false, which should makes the widget uneditable. The message should be displayed in a tooltip. Not clear how to allow the user to get to the stack trace.
* Write failed. This should result in a popup if the user is the initiator of the action.
Errors for pvs that are not user selected/initiated (for example, a write failed for a notification pv) should go to the log.

JavaBeans to BOY property
Properties on the widgets are JavaBeans properties. The process of mapping them to BOY properties could be more automated.

Popups
These should be 3 elements in the popup.
* pv/formula
* value
* configuration (if widget is configurable)

**Comment by berryma4** [comment]
closing project
