### ISSUE TITLE
OSGI diirt bundles (Lead: Gabriele - Reviewers: Eric, Kay)

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#800]
@berryma4 will do the service loader part

**Comment by berryma4** [comment]
For the record, this update to 'master' has been reverted. The issue_800 branch has the corresponding changes.

**Comment by berryma4** [comment]
Current todo:
  - [ ] continue moving plugins from org.epics.vtype to org.diirt.vtype
  - [ ] continue moving plugins from org.epics.utils to org.diirt.utils.*
  - [ ] continue moving plugins from org.epics.pvmanager.* to org.diirt.datasource.* (and similar; source)
  - [ ] resolve service extension point issue
  - [ ] resolve configuration issue

**Comment by gcarcassi** [comment]
The current to do is enable a product build on the cs-studio-4-integration branch. There is going to be no progress until that is done.

**Comment by berryma4** [comment]
currently, pvmanager is taken from a clone for the pva change in the upstream diirt.
artifacts are uploaded to maven.controlsystemstudio.org.

**Comment by shroffk** [comment]
These points are now part of the #1171 Issue
