### ISSUE TITLE
Unicode replacement character U+FFFD is shown instead of NaN on Text Update Widget

### ISSUE THREAD

**Issue by mfurseman** [ControlSystemStudio/cs-studio#807]
When a PV has a NaN value this is displayed differently on the Text Update widget depending on whether the 'Precision from PV' option is checked.

This image shows two Text Updates and a Text Label attached to the same local PV, the one on the right has Precision from PV checked, the one on the left doesn't.

![nan-test](https://cloud.githubusercontent.com/assets/5279818/4975444/4ed83250-68d0-11e4-9ddf-2fec0b7b9412.png)

This is addressed by pull request #806

**Comment by kasemir** [comment]
I think this has been fixed, closing
