### ISSUE TITLE
Repo clean up for easing development 

### ISSUE THREAD

**Issue by berryma4** [ControlSystemStudio/cs-studio#818]
Main two issues:
 - need to build only what changed
 - timestamp, qualifier, snapshot issue

**Comment by shroffk** [comment]
module creation - Issue_818 branch in the main cs-studio repo for preparing the restructured repo
Archive (FRIB, BNL)
Databrowser (SNS)
Scan (SNS)
Shift (BNL)
OpiBuilder (SNS)
Utility (BNL)
Diag (BNL)

features
- new features if necessary
- clean up features (included plugins)

https://openepics.ci.cloudbees.com/view/CS-Studio-Applications/
create cloudbees jobs to build these modules.

**Comment by kasemir** [comment]
@shroffk @berryma4 Since I'm done with my list of opibuilder, scan, databrowser, I've moved archive to my list as well because its my code after all. If you're already in the middle of doing that one, then of course proceed, otherwise I'll likely handle it early next week.

**Comment by shroffk** [comment]
Please feel free to move the archiver too.
I am planning to work on my part early next week (this week I have been distracted with the connections and macro fun stuff...)

**Comment by shroffk** [comment]
NOTE: git follows renamed files, the git history and blame should continue to show all previous commits. It is not possible to follow the changes at a folder level.
If the need be the history can be modified with filter-branch --tree-filter .....

**Comment by berryma4** [comment]
Why are: 
org.csstudio.alarm.beast.test
org.csstudio.apputil.test
org.csstudio.apputil.ui.test
org.csstudio.apputil.ui
org.csstudio.apputil
org.csstudio.opibuilder.alarm

not in respective folders?

**Comment by berryma4** [comment]
We really need to close this out please.
The applications/plugins directory needs to be empty.
Whatever is there on Monday, I will be moving to applications/unorganized.  So we can close this project and release 4.1.

**Comment by shroffk** [comment]
These applications don't exactly fall in any of the modules already set up.

**Comment by kasemir** [comment]
I'll move org.csstudio.alarm.beast.test while fixing #1095.

With org.csstudio.opibuilder.alarm I wasn't sure where it belongs, since it depends on both org.csstudio.opibuilder and org.csstudio.beast.alarm

**Comment by berryma4** [comment]
I vote for org.csstudio.opibuilder.alarm to be with opibuilder :+1:

**Comment by kasemir** [comment]
I can move org.csstudio.opibuilder.alarm into applications/opibuilder.
Will then also need its own feature so that it ends up in the local repo. Shouldn't be included in any of the basic opibuilder or alarm features since I think only KEK uses it in GUI product.

**Comment by kasemir** [comment]
To move org.csstudio.opibuilder.alarm into applications/opibuilder, I first need a 'master' that actually builds, i.e. #1099

**Comment by berryma4** [comment]
build a thon closes this issue
