### ISSUE TITLE
Allow unsigned data in intensity graph

### ISSUE THREAD

**Issue by mfurseman** [ControlSystemStudio/cs-studio#823]
This issue references pull request #822 .

We have a waveform of type DBR_BYTE which we want to display in the intensity graph, the data uses the full unsigned range 0..255. When the graph recieves the data it is in an array of double values with range -128..127, note that the negative data shold be 'on top' of the positive data but it isn't beacuse the conversion seems to assume signed bytes.

The pull request essentailly adds values to the negative data points so the data is in the range 0..255 again, with the neccassary properties added to allow you to choose if you want this 'unsigned behaviour' and how long the data is.

Although this solves the problem we are having it seems like it should be possible to get the unsigned data from somewhere further upstream.

**Comment by shroffk** [comment]
Even if we move cs-studio to java8, I think we might have to update CAJ first.

**Comment by berryma4** [comment]
@willrogers what was your fix for this?  (I have the same issue today)

**Comment by mfurseman** [comment]
For our product we import the [DAWN widgets](https://github.com/DawnScience/swt-xy-graph) and wrap them for BOY. We [added](https://github.com/DawnScience/swt-xy-graph/pull/5/files#diff-df07ed56aaed731847568422d054da4c) the unsigned data features to these widgets. These were originally taken from BOY, and I think there is work underway to unify them with the Eclipse Nebula project.
