### ISSUE TITLE
Eclipse contributed menu items are not relevant in CS-Studio

### ISSUE THREAD

**Issue by mfurseman** [ControlSystemStudio/cs-studio#884]
There menu items included with some of the Eclipse plugins, however they don't seem suitable in CS-Studio. For instance the 'File->Convert Line Delimiters To' menu item, and the ones outlined below to perform file navigation in an Editor:

![cs-studio-menu-buttons](https://cloud.githubusercontent.com/assets/5279818/5778890/63857faa-9d96-11e4-93d4-7460ad079b10.png)

Although there may be applications for these items they are distracting when using Diamonds implementaion of CSS.

The menu actions can be removed using an internal API:
https://github.com/dls-controls/cs-studio/compare/ControlSystemStudio:4.0.x...menu-cleanup-4.0.x

**Comment by berryma4** [comment]
I agree with this change, can you submit a pull request. @kasemir , your
thoughts?

**Comment by kasemir** [comment]
Yes, good!
Just add comments to the code that it's intenal API, and why we use it.

**Comment by kasemir** [comment]
Somewhat related, in case somebody later checks this ticket about unwanted menu entries:
`NoResourceEditorInput` from https://github.com/ControlSystemStudio/cs-studio/blob/master/core/plugins/org.csstudio.ui.util/src/org/csstudio/ui/util/NoResourceEditorInput.java can be used to remove irrelevant context menu entries for "Editors" that happen to related to a "IFile".

**Comment by kasemir** [comment]
I think this can be closed, since the related pull requests have been merged.

**Comment by berryma4** [comment]
Sorry, I usually close the issue after it gets merged to master.
