### ISSUE TITLE
RAP Databrowser and OPI no longer work

### ISSUE THREAD

**Issue by css-iter** [ControlSystemStudio/cs-studio#967]
The webdatabrowser and webopi no longer work. Two reasons:
1. Refactorization of the databrowser plugin, which now uses a different charting library
2. General plugin reorganization. Some plugins have been removed and some new dependencies introduced.

**Comment by kasemir** [comment]
Thanks for updating the RAP build!

**Comment by kasemir** [comment]
I think the original issue had been resolved, but as the opibuilder and databrowser code just moved into their own applications/* subdirs, might be good to confirm that the RAP build survived that change.
