### ISSUE TITLE
org.csstudio.autocomplete.logbook could move from applications/plugins to applications/logbook/logbook-plugins

### ISSUE THREAD

**Issue by richardfearn** [ControlSystemStudio/cs-studio#982]
It depends on `org.csstudio.autocomplete` (which is in `core`) and `org.csstudio.logbook` (which is of course already in `applications/logbook/logbook-plugins`).

`org.csstudio.logbook.viewer` depends on it.

It's currently included in `org.csstudio.applications.all.feature`.

**Comment by berryma4** [comment]
Yes!!  Please do help with the reorg project: #818
@shroffk is on vacation, but that's no reason for the fun to stop.
