### ISSUE TITLE
DataBrowser: part of plot disappears after zooming in

### ISSUE THREAD

**Issue by mark0n** [ControlSystemStudio/cs-studio#993]
When I zoom in part of my data disappears. See [screen cast](http://youtu.be/UDpr00g7TkY) for details. Note that the data disappears after a few seconds which probably means this happens after querying the archiver.

I'm running CS-Studio 4.0.4 on Kubuntu 14.10.

**Comment by kasemir** [comment]
Your video shows the older data browser, before a rather comprehensive update ~2 month ago.

**Comment by berryma4** [comment]
Martin,

4.1 is in projects/css/release/testing

This is just a one time snapshot of master ... I didn't quite finish the
Jenkins job builder before I left.

**Comment by berryma4** [comment]
new databrowser won't fix
